# Format Transfer

## 宋史

In [ ]:
import os
from bs4 import BeautifulSoup

# Define the base directory
base_directory = '/content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/'

# Check if Google Drive is mounted
if not os.path.exists('/content/drive'):
    print("Error: Google Drive not mounted. Please mount your Google Drive first.")
elif not os.path.exists(base_directory):
    print(f"Error: Base directory '{base_directory}' not found. Please ensure the path is correct.")
else:
    print(f"Processing files in subdirectories under: {base_directory}")

    # Iterate through volumes from 242 to 496
    for volume_num in range(242, 497):
        volume_dir_name = f'宋史_卷{volume_num}'
        current_directory_path = os.path.join(base_directory, volume_dir_name)

        if not os.path.exists(current_directory_path):
            print(f"Warning: Directory '{current_directory_path}' not found. Skipping.")
            continue

        print(f"\nProcessing volume directory: {current_directory_path}")
        # Iterate over all files in the current volume directory
        for filename in os.listdir(current_directory_path):
            if filename.endswith('.html') or filename.endswith('.htm'):
                html_filepath = os.path.join(current_directory_path, filename)
                txt_filename = os.path.splitext(filename)[0] + '.txt'
                txt_filepath = os.path.join(current_directory_path, txt_filename)

                try:
                    with open(html_filepath, 'r', encoding='utf-8') as f:
                        html_content = f.read()

                    # Parse HTML and extract text
                    soup = BeautifulSoup(html_content, 'html.parser')
                    # Get text, using a space as separator and stripping extra whitespace
                    text_content = soup.get_text(separator=' ', strip=True)

                    # Save the text content to a new .txt file
                    with open(txt_filepath, 'w', encoding='utf-8') as f:
                        f.write(text_content)
                    print(f"Converted '{filename}' to '{txt_filename}' in '{volume_dir_name}'")
                except Exception as e:
                    print(f"Error processing '{filename}' in '{volume_dir_name}': {e}")
    print("\nConversion of all specified volumes complete.")

Processing files in subdirectories under: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷242
Converted 'index.html' to 'index.txt' in '宋史_卷242'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷243
Converted 'index.html' to 'index.txt' in '宋史_卷243'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷244
Converted 'index.html' to 'index.txt' in '宋史_卷244'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷245
Converted 'index.html' to 'index.txt' in '宋史_卷245'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷246
Converted 'index.html' to 'index.txt' in '宋史_卷246'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷247
Converted 'index.html' to 'index.txt' in '宋史_卷247'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷248
Converted 'index.html' to 'index.txt' in '宋史_卷248'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷249
Converted 'index.html' to 'index.txt' in '宋史_卷249'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷250
Converted 'index.html' to 'index.txt' in '宋史_卷250'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷251
Converted 'index.html' to 'index.txt' in '宋史_卷251'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷252
Converted 'index.html' to 'index.txt' in '宋史_卷252'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷253
Converted 'index.html' to 'index.txt' in '宋史_卷253'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷254
Converted 'index.html' to 'index.txt' in '宋史_卷254'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷255
Converted 'index.html' to 'index.txt' in '宋史_卷255'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷256
Converted 'index.html' to 'index.txt' in '宋史_卷256'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷257
Converted 'index.html' to 'index.txt' in '宋史_卷257'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷258
Converted 'index.html' to 'index.txt' in '宋史_卷258'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷259
Converted 'index.html' to 'index.txt' in '宋史_卷259'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷260
Converted 'index.html' to 'index.txt' in '宋史_卷260'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷261
Converted 'index.html' to 'index.txt' in '宋史_卷261'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷262
Converted 'index.html' to 'index.txt' in '宋史_卷262'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷263
Converted 'index.html' to 'index.txt' in '宋史_卷263'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷264
Converted 'index.html' to 'index.txt' in '宋史_卷264'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷265
Converted 'index.html' to 'index.txt' in '宋史_卷265'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷266
Converted 'index.html' to 'index.txt' in '宋史_卷266'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷267
Converted 'index.html' to 'index.txt' in '宋史_卷267'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷268
Converted 'index.html' to 'index.txt' in '宋史_卷268'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷269
Converted 'index.html' to 'index.txt' in '宋史_卷269'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷270
Converted 'index.html' to 'index.txt' in '宋史_卷270'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷271
Converted 'index.html' to 'index.txt' in '宋史_卷271'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷272
Converted 'index.html' to 'index.txt' in '宋史_卷272'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷273
Converted 'index.html' to 'index.txt' in '宋史_卷273'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷274
Converted 'index.html' to 'index.txt' in '宋史_卷274'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷275
Converted 'index.html' to 'index.txt' in '宋史_卷275'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷276
Converted 'index.html' to 'index.txt' in '宋史_卷276'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷277
Converted 'index.html' to 'index.txt' in '宋史_卷277'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷278
Converted 'index.html' to 'index.txt' in '宋史_卷278'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷279
Converted 'index.html' to 'index.txt' in '宋史_卷279'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷280
Converted 'index.html' to 'index.txt' in '宋史_卷280'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷281
Converted 'index.html' to 'index.txt' in '宋史_卷281'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷282
Converted 'index.html' to 'index.txt' in '宋史_卷282'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷283
Converted 'index.html' to 'index.txt' in '宋史_卷283'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷284
Converted 'index.html' to 'index.txt' in '宋史_卷284'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷285
Converted 'index.html' to 'index.txt' in '宋史_卷285'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷286
Converted 'index.html' to 'index.txt' in '宋史_卷286'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷287
Converted 'index.html' to 'index.txt' in '宋史_卷287'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷288
Converted 'index.html' to 'index.txt' in '宋史_卷288'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷289
Converted 'index.html' to 'index.txt' in '宋史_卷289'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷290
Converted 'index.html' to 'index.txt' in '宋史_卷290'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷291
Converted 'index.html' to 'index.txt' in '宋史_卷291'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷292
Converted 'index.html' to 'index.txt' in '宋史_卷292'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷293
Converted 'index.html' to 'index.txt' in '宋史_卷293'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷294
Converted 'index.html' to 'index.txt' in '宋史_卷294'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷295
Converted 'index.html' to 'index.txt' in '宋史_卷295'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷296
Converted 'index.html' to 'index.txt' in '宋史_卷296'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷297
Converted 'index.html' to 'index.txt' in '宋史_卷297'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷298
Converted 'index.html' to 'index.txt' in '宋史_卷298'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷299
Converted 'index.html' to 'index.txt' in '宋史_卷299'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷300
Converted 'index.html' to 'index.txt' in '宋史_卷300'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷301
Converted 'index.html' to 'index.txt' in '宋史_卷301'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷302
Converted 'index.html' to 'index.txt' in '宋史_卷302'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷303
Converted 'index.html' to 'index.txt' in '宋史_卷303'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷304
Converted 'index.html' to 'index.txt' in '宋史_卷304'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷305
Converted 'index.html' to 'index.txt' in '宋史_卷305'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷306
Converted 'index.html' to 'index.txt' in '宋史_卷306'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷307
Converted 'index.html' to 'index.txt' in '宋史_卷307'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷308
Converted 'index.html' to 'index.txt' in '宋史_卷308'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷309
Converted 'index.html' to 'index.txt' in '宋史_卷309'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷310
Converted 'index.html' to 'index.txt' in '宋史_卷310'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷311
Converted 'index.html' to 'index.txt' in '宋史_卷311'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷312
Converted 'index.html' to 'index.txt' in '宋史_卷312'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷313
Converted 'index.html' to 'index.txt' in '宋史_卷313'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷314
Converted 'index.html' to 'index.txt' in '宋史_卷314'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷315
Converted 'index.html' to 'index.txt' in '宋史_卷315'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷316
Converted 'index.html' to 'index.txt' in '宋史_卷316'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷317
Converted 'index.html' to 'index.txt' in '宋史_卷317'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷318
Converted 'index.html' to 'index.txt' in '宋史_卷318'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷319
Converted 'index.html' to 'index.txt' in '宋史_卷319'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷320
Converted 'index.html' to 'index.txt' in '宋史_卷320'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷321
Converted 'index.html' to 'index.txt' in '宋史_卷321'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷322
Converted 'index.html' to 'index.txt' in '宋史_卷322'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷323
Converted 'index.html' to 'index.txt' in '宋史_卷323'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷324
Converted 'index.html' to 'index.txt' in '宋史_卷324'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷325
Converted 'index.html' to 'index.txt' in '宋史_卷325'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷326
Converted 'index.html' to 'index.txt' in '宋史_卷326'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷327
Converted 'index.html' to 'index.txt' in '宋史_卷327'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷328
Converted 'index.html' to 'index.txt' in '宋史_卷328'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷329
Converted 'index.html' to 'index.txt' in '宋史_卷329'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷330
Converted 'index.html' to 'index.txt' in '宋史_卷330'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷331
Converted 'index.html' to 'index.txt' in '宋史_卷331'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷332
Converted 'index.html' to 'index.txt' in '宋史_卷332'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷333
Converted 'index.html' to 'index.txt' in '宋史_卷333'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷334
Converted 'index.html' to 'index.txt' in '宋史_卷334'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷335
Converted 'index.html' to 'index.txt' in '宋史_卷335'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷336
Converted 'index.html' to 'index.txt' in '宋史_卷336'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷337
Converted 'index.html' to 'index.txt' in '宋史_卷337'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷338
Converted 'index.html' to 'index.txt' in '宋史_卷338'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷339
Converted 'index.html' to 'index.txt' in '宋史_卷339'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷340
Converted 'index.html' to 'index.txt' in '宋史_卷340'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷341
Converted 'index.html' to 'index.txt' in '宋史_卷341'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷342
Converted 'index.html' to 'index.txt' in '宋史_卷342'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷343
Converted 'index.html' to 'index.txt' in '宋史_卷343'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷344
Converted 'index.html' to 'index.txt' in '宋史_卷344'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷345
Converted 'index.html' to 'index.txt' in '宋史_卷345'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷346
Converted 'index.html' to 'index.txt' in '宋史_卷346'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷347
Converted 'index.html' to 'index.txt' in '宋史_卷347'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷348
Converted 'index.html' to 'index.txt' in '宋史_卷348'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷349
Converted 'index.html' to 'index.txt' in '宋史_卷349'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷350
Converted 'index.html' to 'index.txt' in '宋史_卷350'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷351
Converted 'index.html' to 'index.txt' in '宋史_卷351'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷352
Converted 'index.html' to 'index.txt' in '宋史_卷352'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷353
Converted 'index.html' to 'index.txt' in '宋史_卷353'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷354
Converted 'index.html' to 'index.txt' in '宋史_卷354'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷355
Converted 'index.html' to 'index.txt' in '宋史_卷355'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷356
Converted 'index.html' to 'index.txt' in '宋史_卷356'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷357
Converted 'index.html' to 'index.txt' in '宋史_卷357'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷358
Converted 'index.html' to 'index.txt' in '宋史_卷358'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷359
Converted 'index.html' to 'index.txt' in '宋史_卷359'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷360
Converted 'index.html' to 'index.txt' in '宋史_卷360'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷361
Converted 'index.html' to 'index.txt' in '宋史_卷361'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷362
Converted 'index.html' to 'index.txt' in '宋史_卷362'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷363
Converted 'index.html' to 'index.txt' in '宋史_卷363'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷364
Converted 'index.html' to 'index.txt' in '宋史_卷364'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷365
Converted 'index.html' to 'index.txt' in '宋史_卷365'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷366
Converted 'index.html' to 'index.txt' in '宋史_卷366'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷367
Converted 'index.html' to 'index.txt' in '宋史_卷367'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷368
Converted 'index.html' to 'index.txt' in '宋史_卷368'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷369
Converted 'index.html' to 'index.txt' in '宋史_卷369'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷370
Converted 'index.html' to 'index.txt' in '宋史_卷370'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷371
Converted 'index.html' to 'index.txt' in '宋史_卷371'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷372
Converted 'index.html' to 'index.txt' in '宋史_卷372'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷373
Converted 'index.html' to 'index.txt' in '宋史_卷373'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷374
Converted 'index.html' to 'index.txt' in '宋史_卷374'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷375
Converted 'index.html' to 'index.txt' in '宋史_卷375'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷376
Converted 'index.html' to 'index.txt' in '宋史_卷376'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷377
Converted 'index.html' to 'index.txt' in '宋史_卷377'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷378
Converted 'index.html' to 'index.txt' in '宋史_卷378'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷379
Converted 'index.html' to 'index.txt' in '宋史_卷379'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷380
Converted 'index.html' to 'index.txt' in '宋史_卷380'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷381
Converted 'index.html' to 'index.txt' in '宋史_卷381'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷382
Converted 'index.html' to 'index.txt' in '宋史_卷382'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷383
Converted 'index.html' to 'index.txt' in '宋史_卷383'

Processing volume directory: /content/drive/MyDrive/NTU/研究/LLM Hackathon/宋史_列傳/宋史_卷384
Converted 'index.html' to 'index.txt' in '宋史_卷384'


In [ ]:
# ============================================================
# 明史 卷113～卷332
# HTML → TXT
# TXT 儲存於各自原本的資料夾
# ============================================================

from google.colab import drive
from pathlib import Path
from bs4 import BeautifulSoup

# ============================================================
# 1. 掛載 Google Drive
# ============================================================

drive.mount('/content/drive')

# ============================================================
# 2. 基本路徑
# ============================================================

base_path = Path(
    "/content/drive/MyDrive/NTU/研究/LLM Hackathon/明史_列傳"
)

START_VOLUME = 113
END_VOLUME = 332

# ============================================================
# 3. 統計
# ============================================================

total_folders = 0
missing_folders = 0
total_html = 0
success_count = 0
error_count = 0

# ============================================================
# 4. 逐一處理「明史_卷113」～「明史_卷332」
# ============================================================

for volume in range(START_VOLUME, END_VOLUME + 1):

    # --------------------------------------------------------
    # 建立資料夾路徑
    # --------------------------------------------------------

    folder = base_path / f"明史_卷{volume}"

    # --------------------------------------------------------
    # 檢查資料夾是否存在
    # --------------------------------------------------------

    if not folder.exists():
        print(f"⚠ 找不到資料夾：{folder}")
        missing_folders += 1
        continue

    total_folders += 1

    print("\n" + "=" * 70)
    print(f"處理：明史_卷{volume}")
    print("=" * 70)

    # --------------------------------------------------------
    # 找出該資料夾內的 HTML
    # --------------------------------------------------------

    html_files = list(folder.glob("*.html")) + list(folder.glob("*.htm"))

    print(f"找到 {len(html_files)} 個 HTML 檔案")

    total_html += len(html_files)

    # --------------------------------------------------------
    # 逐一轉換
    # --------------------------------------------------------

    for html_file in sorted(html_files):

        try:

            # =================================================
            # 讀取 HTML
            # =================================================

            with open(
                html_file,
                "r",
                encoding="utf-8",
                errors="replace"
            ) as f:
                html_content = f.read()

            # =================================================
            # BeautifulSoup 解析 HTML
            # =================================================

            soup = BeautifulSoup(
                html_content,
                "html.parser"
            )

            # =================================================
            # 移除 script / style / noscript
            # =================================================

            for tag in soup(["script", "style", "noscript"]):
                tag.decompose()

            # =================================================
            # 取得純文字
            # =================================================

            text = soup.get_text(separator="\n")

            # =================================================
            # 清理文字
            # =================================================

            text = text.replace("\r\n", "\n")
            text = text.replace("\r", "\n")

            # 每行去除前後空白
            lines = [
                line.strip()
                for line in text.split("\n")
            ]

            # -------------------------------------------------
            # 移除連續空白行
            # -------------------------------------------------

            cleaned_lines = []
            previous_blank = False

            for line in lines:

                if line == "":

                    if not previous_blank:
                        cleaned_lines.append("")

                    previous_blank = True

                else:

                    cleaned_lines.append(line)
                    previous_blank = False

            text = "\n".join(cleaned_lines).strip()

            # =================================================
            # TXT 檔案路徑
            # =================================================

            txt_file = html_file.with_suffix(".txt")

            # =================================================
            # 儲存 TXT
            # =================================================

            with open(
                txt_file,
                "w",
                encoding="utf-8"
            ) as f:

                f.write(text)

            success_count += 1

            print(f"  ✓ {html_file.name} → {txt_file.name}")

        except Exception as e:

            error_count += 1

            print(f"  ✗ {html_file.name}")
            print(f"    錯誤：{e}")

# ============================================================
# 5. 最終統計
# ============================================================

print("\n")
print("=" * 70)
print("                 HTML → TXT 轉換完成")
print("=" * 70)

print(f"處理範圍：明史_卷{START_VOLUME} ～ 明史_卷{END_VOLUME}")
print(f"應處理資料夾：{END_VOLUME - START_VOLUME + 1}")
print(f"找到資料夾：{total_folders}")
print(f"找不到資料夾：{missing_folders}")
print(f"HTML 檔案總數：{total_html}")
print(f"成功轉換：{success_count}")
print(f"轉換失敗：{error_count}")

print("\nTXT 儲存位置：")
print(base_path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

======================================================================
處理：明史_卷113
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷114
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷115
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷116
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷117
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷118
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷119
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷120
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷121
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷122
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷123
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷124
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷125
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷126
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷127
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷128
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷129
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷130
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷131
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷132
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷133
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷134
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷135
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷136
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷137
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷138
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷139
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷140
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷141
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷142
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷143
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷144
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷145
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷146
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷147
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷148
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷149
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷150
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷151
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷152
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷153
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷154
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷155
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷156
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷157
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷158
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷159
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷160
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷161
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷162
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷163
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷164
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷165
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷166
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷167
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷168
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷169
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷170
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷171
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷172
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷173
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷174
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷175
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷176
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷177
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷178
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷179
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷180
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷181
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷182
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷183
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷184
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷185
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷186
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷187
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷188
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷189
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷190
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷191
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷192
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷193
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷194
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷195
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷196
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷197
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷198
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷199
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷200
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷201
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷202
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷203
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷204
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷205
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷206
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷207
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷208
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷209
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷210
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷211
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷212
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================
處理：明史_卷213
======================================================================
找到 1 個 HTML 檔案
  ✓ index.html → index.txt

======================================================================

# Cosine similarity

In [9]:
import os
import json
import glob

# ==========================================================
# Settings
# ==========================================================

folder_path = "/content/"


# ==========================================================
# Find all JSON files
# ==========================================================

json_files = sorted(
    glob.glob(
        os.path.join(folder_path, "*.json")
    )
)

print(f"找到 {len(json_files)} 個 JSON 檔案\n")


# ==========================================================
# Read JSON files
# ==========================================================

all_data = {}

for file_path in json_files:

    file_name = os.path.basename(file_path)

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        all_data[file_name] = data

        if isinstance(data, list):
            print(f"✓ {file_name}: {len(data):,} 筆")

        elif isinstance(data, dict):
            print(f"✓ {file_name}: {len(data):,} 個 keys")

        else:
            print(f"✓ {file_name}: {type(data).__name__}")

    except Exception as e:
        print(f"✗ {file_name}: 讀取失敗")
        print(f"  Error: {e}")


# ==========================================================
# Summary
# ==========================================================

print("\n" + "=" * 60)
print("讀取完成")
print("=" * 60)

print(f"JSON 檔案數量：{len(all_data):,}")
print("\n檔案名稱：")

for file_name in all_data:
    print(f"  - {file_name}")

找到 10 個 JSON 檔案

✓ INSCR-KR4d0232-WYG-f006-0002.json: 1 個 keys
✓ INSCR-KR4d0466-WYG-f011-0010.json: 1 個 keys
✓ annotations_enc_rotary_cmn_SPSP192506121501.json: 1 個 keys
✓ annotations_enc_rotary_cmn_SPSP193109022001.json: 1 個 keys
✓ annotations_enc_rotary_en_1319843498.json: 1 個 keys
✓ annotations_enc_rotary_en_1319854677.json: 1 個 keys
✓ po_en_1.json: 1 個 keys
✓ po_en_1669.json: 1 個 keys
✓ structure_example_TW_po_zh_2376.json: 1 個 keys
✓ structure_example_TW_po_zh_8342_ZC.json: 1 個 keys

============================================================
讀取完成
============================================================
JSON 檔案數量：10

檔案名稱：
  - INSCR-KR4d0232-WYG-f006-0002.json
  - INSCR-KR4d0466-WYG-f011-0010.json
  - annotations_enc_rotary_cmn_SPSP192506121501.json
  - annotations_enc_rotary_cmn_SPSP193109022001.json
  - annotations_enc_rotary_en_1319843498.json
  - annotations_enc_rotary_en_1319854677.json
  - po_en_1.json
  - po_en_1669.json
  - structure_example_TW_po_zh_2376.json
  - structure_example_TW_po_zh_8342_ZC.json

## Chinese

In [17]:
# ==========================================================
# Chinese Event Name Cosine Similarity
# TF-IDF Character N-gram
# 保留 event_id
# ==========================================================

import os
import json
import glob
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# ==========================================================
# 1. Settings
# ==========================================================

folder_path = "/content/"

# Character n-gram
# 中文例如：
# 始作浮梁
# 浮梁建橋
# 建造浮梁橋
NGRAM_RANGE = (1, 3)


# ==========================================================
# 2. Find JSON files
# ==========================================================

json_files = sorted(
    glob.glob(
        os.path.join(folder_path, "*.json")
    )
)

print("=" * 70)
print("JSON files")
print("=" * 70)

print(f"找到 {len(json_files)} 個 JSON 檔案")

for file_path in json_files:
    print(" -", os.path.basename(file_path))


# ==========================================================
# 3. Read JSON and extract Chinese events
#
# 中文 JSON 結構：
#
# {
#     "topic_record": {
#         "sources": [...],
#         "events": [...]
#     }
# }
# ==========================================================

events = []

for file_path in json_files:

    file_name = os.path.basename(file_path)

    with open(
        file_path,
        "r",
        encoding="utf-8"
    ) as f:

        data = json.load(f)


    # ------------------------------------------------------
    # topic_record
    # ------------------------------------------------------

    topic_record = data.get(
        "topic_record",
        {}
    )


    # ------------------------------------------------------
    # events
    # ------------------------------------------------------

    event_list = topic_record.get(
        "events",
        []
    )


    print(
        f"\n{file_name}: "
        f"{len(event_list)} events"
    )


    # ------------------------------------------------------
    # Extract event_id + event_name
    # ------------------------------------------------------

    for event in event_list:

        event_id = event.get(
            "event_id"
        )

        event_name = event.get(
            "event_name"
        )


        if event_name is None:
            continue


        event_name = str(
            event_name
        ).strip()


        if event_name == "":
            continue


        events.append({

            "event_id":
                event_id,

            "event_name":
                event_name,

            "source_file":
                file_name
        })


# ==========================================================
# 4. DataFrame
# ==========================================================

events_df = pd.DataFrame(
    events
)


print("\n" + "=" * 70)
print("Event data")
print("=" * 70)

print(
    f"Event 總數："
    f"{len(events_df):,}"
)

print(
    f"不同 event_name："
    f"{events_df['event_name'].nunique():,}"
)

print(
    f"不同 event_id："
    f"{events_df['event_id'].nunique():,}"
)


display(
    events_df.head(20)
)


# ==========================================================
# 5. Unique Events
#
# 不只用 event_name 去重
#
# 以 event_id + event_name 為唯一事件
#
# 避免：
# 不同 event_id
# 但 event_name 相同
# 被錯誤合併
# ==========================================================

unique_events_df = (
    events_df[
        [
            "event_id",
            "event_name",
            "source_file"
        ]
    ]
    .drop_duplicates(
        subset=[
            "event_id",
            "event_name"
        ]
    )
    .reset_index(drop=True)
)


print("\n" + "=" * 70)
print("Unique Events")
print("=" * 70)

print(
    f"Unique Event 數："
    f"{len(unique_events_df):,}"
)


display(
    unique_events_df
)


# ==========================================================
# 6. TF-IDF
# ==========================================================

vectorizer = TfidfVectorizer(

    # Character-level
    analyzer="char",

    # 中文 Character N-gram
    ngram_range=NGRAM_RANGE,

    # 保留設定
    lowercase=True,

    min_df=1
)


tfidf_matrix = vectorizer.fit_transform(
    unique_events_df["event_name"]
)


print("\n" + "=" * 70)
print("TF-IDF")
print("=" * 70)

print(
    "TF-IDF matrix shape:",
    tfidf_matrix.shape
)


# ==========================================================
# 7. Cosine Similarity
# ==========================================================

similarity_matrix = cosine_similarity(
    tfidf_matrix
)


# ==========================================================
# 8. Similarity Matrix
#
# 使用 event_id 作為 index / columns
# ==========================================================

similarity_df = pd.DataFrame(
    similarity_matrix,
    index=unique_events_df["event_id"],
    columns=unique_events_df["event_id"]
)


print("\n" + "=" * 70)
print("Cosine Similarity Matrix")
print("=" * 70)

display(
    similarity_df.round(4)
)


# ==========================================================
# 9. Pairwise Similarity
#
# 保留：
# event_id_1
# event_name_1
# event_id_2
# event_name_2
# cosine_similarity
# ==========================================================

pairwise_results = []


for i in range(
    len(unique_events_df)
):

    for j in range(
        i + 1,
        len(unique_events_df)
    ):

        pairwise_results.append({

            "event_id_1":
                unique_events_df.loc[
                    i,
                    "event_id"
                ],

            "event_name_1":
                unique_events_df.loc[
                    i,
                    "event_name"
                ],

            "event_id_2":
                unique_events_df.loc[
                    j,
                    "event_id"
                ],

            "event_name_2":
                unique_events_df.loc[
                    j,
                    "event_name"
                ],

            "cosine_similarity":
                similarity_matrix[i, j]
        })


pairwise_df = pd.DataFrame(
    pairwise_results
)


# ==========================================================
# 10. Sort Similarity
# ==========================================================

pairwise_df = (
    pairwise_df
    .sort_values(
        "cosine_similarity",
        ascending=False
    )
    .reset_index(drop=True)
)


print("\n" + "=" * 70)
print("Pairwise Cosine Similarity")
print("=" * 70)

display(
    pairwise_df.round(4)
)


# ==========================================================
# 11. Save original Event data
# ==========================================================

events_path = (
    "/content/"
    "chinese_event_events.csv"
)


events_df.to_csv(
    events_path,
    index=False,
    encoding="utf-8-sig"
)


# ==========================================================
# 12. Save Event mapping
# ==========================================================

mapping_path = (
    "/content/"
    "chinese_event_mapping.csv"
)


unique_events_df.to_csv(
    mapping_path,
    index=False,
    encoding="utf-8-sig"
)


# ==========================================================
# 13. Save Similarity Matrix
# ==========================================================

matrix_path = (
    "/content/"
    "chinese_event_cosine_similarity_matrix.csv"
)


similarity_df.to_csv(
    matrix_path,
    encoding="utf-8-sig"
)


# ==========================================================
# 14. Save Pairwise Similarity
# ==========================================================

pairwise_path = (
    "/content/"
    "chinese_event_cosine_similarity_pairwise.csv"
)


pairwise_df.to_csv(
    pairwise_path,
    index=False,
    encoding="utf-8-sig"
)


# ==========================================================
# 15. 完成
# ==========================================================

print("\n" + "=" * 70)
print("完成")
print("=" * 70)

print(
    "\nEvent data：",
    events_path
)

print(
    "Event mapping：",
    mapping_path
)

print(
    "Similarity matrix：",
    matrix_path
)

print(
    "Pairwise results：",
    pairwise_path
)

======================================================================
JSON files
======================================================================
找到 10 個 JSON 檔案
 - INSCR-KR4d0232-WYG-f006-0002.json
 - INSCR-KR4d0466-WYG-f011-0010.json
 - annotations_enc_rotary_cmn_SPSP192506121501.json
 - annotations_enc_rotary_cmn_SPSP193109022001.json
 - annotations_enc_rotary_en_1319843498.json
 - annotations_enc_rotary_en_1319854677.json
 - po_en_1.json
 - po_en_1669.json
 - structure_example_TW_po_zh_2376.json
 - structure_example_TW_po_zh_8342_ZC.json

INSCR-KR4d0232-WYG-f006-0002.json: 4 events

INSCR-KR4d0466-WYG-f011-0010.json: 5 events

annotations_enc_rotary_cmn_SPSP192506121501.json: 2 events

annotations_enc_rotary_cmn_SPSP193109022001.json: 2 events

annotations_enc_rotary_en_1319843498.json: 0 events

annotations_enc_rotary_en_1319854677.json: 0 events

po_en_1.json: 0 events

po_en_1669.json: 0 events

structure_example_TW_po_zh_2376.json: 2 events

structure_example_TW_po_zh_8342_ZC.json: 7 events

======================================================================
Event data
======================================================================
Event 總數：22
不同 event_name：22
不同 event_id：22

,event_id,event_name,source_file
0,INSCR-KR4d0232-WYG-f006-0002_01,始作浮梁,INSCR-KR4d0232-WYG-f006-0002.json
1,INSCR-KR4d0232-WYG-f006-0002_02,漂航斷笮／橋毁,INSCR-KR4d0232-WYG-f006-0002.json
2,INSCR-KR4d0232-WYG-f006-0002_03,造端,INSCR-KR4d0232-WYG-f006-0002.json
3,INSCR-KR4d0232-WYG-f006-0002_04,告具,INSCR-KR4d0232-WYG-f006-0002.json
4,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,INSCR-KR4d0466-WYG-f011-0010.json
5,INSCR-KR4d0466-WYG-f011-0010_02,度材鳩工,INSCR-KR4d0466-WYG-f011-0010.json
6,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json
7,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json
8,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,INSCR-KR4d0466-WYG-f011-0010.json
9,SPSP192506121501_01,天津扶輪社電上海扶輪社日前接天津扶輪社來電略謂天津扶輪社同人敬以同氣之誼致候上海扶輪社諸君並...,annotations_enc_rotary_cmn_SPSP192506121501.json
10,SPSP192506121501_02,該社當即擬覆略謂敬問起居卓見深合私衷同人等正盡力重建相尊相信之原則,annotations_enc_rotary_cmn_SPSP192506121501.json
11,SPSP193109022001_01,扶輪社明日聚餐會上海扶輪社本星期四午間十二時三十分、在老卡爾登舉行聚餐會,annotations_enc_rotary_cmn_SPSP193109022001.json
12,SPSP193109022001_02,請安德魯博士演講最近探險蒙古沙漠情形,annotations_enc_rotary_cmn_SPSP193109022001.json
13,po_zh_2376_00,有關今（二十七）日「中時晚報」及「勁報」報導「總統府公務車撞六車傷五人」乙事，因與事實不符，...,structure_example_TW_po_zh_2376.json
14,po_zh_2376_01,今天上午在台北市羅斯福路所發生疑似暴衝之連環車禍,structure_example_TW_po_zh_2376.json
15,po_zh_8342_00,陳總統水扁先生今天下午前往南投縣埔里鎮參加國道六號南投段開工動土典禮，並應邀致詞。,structure_example_TW_po_zh_8342_ZC.json
16,po_zh_8342_01,今天阿扁非常高興到南投埔里，來參加「新十大建設」在中部地區最重大工程之一：「國道六號南投段」...,structure_example_TW_po_zh_8342_ZC.json
17,po_zh_8342_02,當年政府開發中部橫貫公路,structure_example_TW_po_zh_8342_ZC.json
18,po_zh_8342_03,隨著「第二高速公路」於今年1月全線通車,structure_example_TW_po_zh_8342_ZC.json
19,po_zh_8342_04,十二條「東西向快速道路」、「西濱快速公路」，以及「高速鐵路」於明年十月開始營運通車,structure_example_TW_po_zh_8342_ZC.json

======================================================================
Unique Events
======================================================================
Unique Event 數：22

,event_id,event_name,source_file
0,INSCR-KR4d0232-WYG-f006-0002_01,始作浮梁,INSCR-KR4d0232-WYG-f006-0002.json
1,INSCR-KR4d0232-WYG-f006-0002_02,漂航斷笮／橋毁,INSCR-KR4d0232-WYG-f006-0002.json
2,INSCR-KR4d0232-WYG-f006-0002_03,造端,INSCR-KR4d0232-WYG-f006-0002.json
3,INSCR-KR4d0232-WYG-f006-0002_04,告具,INSCR-KR4d0232-WYG-f006-0002.json
4,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,INSCR-KR4d0466-WYG-f011-0010.json
5,INSCR-KR4d0466-WYG-f011-0010_02,度材鳩工,INSCR-KR4d0466-WYG-f011-0010.json
6,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json
7,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json
8,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,INSCR-KR4d0466-WYG-f011-0010.json
9,SPSP192506121501_01,天津扶輪社電上海扶輪社日前接天津扶輪社來電略謂天津扶輪社同人敬以同氣之誼致候上海扶輪社諸君並...,annotations_enc_rotary_cmn_SPSP192506121501.json
10,SPSP192506121501_02,該社當即擬覆略謂敬問起居卓見深合私衷同人等正盡力重建相尊相信之原則,annotations_enc_rotary_cmn_SPSP192506121501.json
11,SPSP193109022001_01,扶輪社明日聚餐會上海扶輪社本星期四午間十二時三十分、在老卡爾登舉行聚餐會,annotations_enc_rotary_cmn_SPSP193109022001.json
12,SPSP193109022001_02,請安德魯博士演講最近探險蒙古沙漠情形,annotations_enc_rotary_cmn_SPSP193109022001.json
13,po_zh_2376_00,有關今（二十七）日「中時晚報」及「勁報」報導「總統府公務車撞六車傷五人」乙事，因與事實不符，...,structure_example_TW_po_zh_2376.json
14,po_zh_2376_01,今天上午在台北市羅斯福路所發生疑似暴衝之連環車禍,structure_example_TW_po_zh_2376.json
15,po_zh_8342_00,陳總統水扁先生今天下午前往南投縣埔里鎮參加國道六號南投段開工動土典禮，並應邀致詞。,structure_example_TW_po_zh_8342_ZC.json
16,po_zh_8342_01,今天阿扁非常高興到南投埔里，來參加「新十大建設」在中部地區最重大工程之一：「國道六號南投段」...,structure_example_TW_po_zh_8342_ZC.json
17,po_zh_8342_02,當年政府開發中部橫貫公路,structure_example_TW_po_zh_8342_ZC.json
18,po_zh_8342_03,隨著「第二高速公路」於今年1月全線通車,structure_example_TW_po_zh_8342_ZC.json
19,po_zh_8342_04,十二條「東西向快速道路」、「西濱快速公路」，以及「高速鐵路」於明年十月開始營運通車,structure_example_TW_po_zh_8342_ZC.json
20,po_zh_8342_05,過去半年以來，股市與房市不斷加溫,structure_example_TW_po_zh_8342_ZC.json
21,po_zh_8342_06,在開工今天，祝福我們國道工程一切順利,structure_example_TW_po_zh_8342_ZC.json

======================================================================
TF-IDF
======================================================================
TF-IDF matrix shape: (22, 1024)

======================================================================
Cosine Similarity Matrix
======================================================================

event_id,INSCR-KR4d0232-WYG-f006-0002_01,INSCR-KR4d0232-WYG-f006-0002_02,INSCR-KR4d0232-WYG-f006-0002_03,INSCR-KR4d0232-WYG-f006-0002_04,INSCR-KR4d0466-WYG-f011-0010_01,INSCR-KR4d0466-WYG-f011-0010_02,INSCR-KR4d0466-WYG-f011-0010_03,INSCR-KR4d0466-WYG-f011-0010_04,INSCR-KR4d0466-WYG-f011-0010_05,SPSP192506121501_01,...,SPSP193109022001_02,po_zh_2376_00,po_zh_2376_01,po_zh_8342_00,po_zh_8342_01,po_zh_8342_02,po_zh_8342_03,po_zh_8342_04,po_zh_8342_05,po_zh_8342_06
event_id,,,,,,,,,,,,,,,,,,,,,
INSCR-KR4d0232-WYG-f006-0002_01,1.0000,0.0000,0.0,0.0,0.0000,0.0000,0.1211,0.0,0.0799,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0161,0.0000,0.0000
INSCR-KR4d0232-WYG-f006-0002_02,0.0000,1.0000,0.0,0.0,0.0455,0.0000,0.0000,0.0,0.0811,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0284,0.0000
INSCR-KR4d0232-WYG-f006-0002_03,0.0000,0.0000,1.0,0.0,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
INSCR-KR4d0232-WYG-f006-0002_04,0.0000,0.0000,0.0,1.0,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
INSCR-KR4d0466-WYG-f011-0010_01,0.0000,0.0455,0.0,0.0,1.0000,0.0000,0.0000,0.0,0.0000,0.0077,...,0.0000,0.0093,0.0000,0.0000,0.0109,0.0243,0.0192,0.0115,0.0000,0.0000
INSCR-KR4d0466-WYG-f011-0010_02,0.0000,0.0000,0.0,0.0,0.0000,1.0000,0.0000,0.0,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0175,0.0306,0.0000,0.0000,0.0000,0.0000,0.0546
INSCR-KR4d0466-WYG-f011-0010_03,0.1211,0.0000,0.0,0.0,0.0000,0.0000,1.0000,0.0,0.1534,0.0000,...,0.0000,0.1086,0.0000,0.0000,0.0000,0.0000,0.0000,0.0309,0.0000,0.0000
INSCR-KR4d0466-WYG-f011-0010_04,0.0000,0.0000,0.0,0.0,0.0000,0.0000,0.0000,1.0,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
INSCR-KR4d0466-WYG-f011-0010_05,0.0799,0.0811,0.0,0.0,0.0000,0.0000,0.1534,0.0,1.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0204,0.0000,0.0000
SPSP192506121501_01,0.0000,0.0000,0.0,0.0,0.0077,0.0000,0.0000,0.0,0.0000,1.0000,...,0.0064,0.0068,0.0301,0.0227,0.0169,0.0000,0.0077,0.0060,0.0114,0.0152
SPSP192506121501_02,0.0000,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0000,0.0671,...,0.0000,0.0046,0.0069,0.0000,0.0179,0.0148,0.0000,0.0000,0.0000,0.0000
SPSP193109022001_01,0.0000,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0000,0.2956,...,0.0000,0.0197,0.0208,0.0055,0.0123,0.0000,0.0072,0.0402,0.0000,0.0073
SPSP193109022001_02,0.0000,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0000,0.0064,...,1.0000,0.0000,0.0000,0.0000,0.0091,0.0000,0.0000,0.0000,0.0000,0.0000
po_zh_2376_00,0.0000,0.0000,0.0,0.0,0.0093,0.0000,0.1086,0.0,0.0000,0.0068,...,0.0000,1.0000,0.0127,0.0478,0.0588,0.0416,0.0652,0.0979,0.0255,0.0122
po_zh_2376_01,0.0000,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0000,0.0301,...,0.0000,0.0127,1.0000,0.0329,0.0253,0.0305,0.0263,0.0235,0.0296,0.0496
po_zh_8342_00,0.0000,0.0000,0.0,0.0,0.0000,0.0175,0.0000,0.0,0.0000,0.0227,...,0.0000,0.0478,0.0329,1.0000,0.2570,0.0081,0.0050,0.0117,0.0150,0.0810
po_zh_8342_01,0.0000,0.0000,0.0,0.0,0.0109,0.0306,0.0000,0.0,0.0000,0.0169,...,0.0091,0.0588,0.0253,0.2570,1.0000,0.0394,0.0384,0.0696,0.0212,0.1197
po_zh_8342_02,0.0000,0.0000,0.0,0.0,0.0243,0.0000,0.0000,0.0,0.0000,0.0000,...,0.0000,0.0416,0.0305,0.0081,0.0394,1.0000,0.0612,0.0614,0.0152,0.0127
po_zh_8342_03,0.0000,0.0000,0.0,0.0,0.0192,0.0000,0.0000,0.0,0.0000,0.0077,...,0.0000,0.0652,0.0263,0.0050,0.0384,0.0612,1.0000,0.2624,0.0120,0.0078
po_zh_8342_04,0.0161,0.0000,0.0,0.0,0.0115,0.0000,0.0309,0.0,0.0204,0.0060,...,0.0000,0.0979,0.0235,0.0117,0.0696,0.0614,0.2624,1.0000,0.0210,0.0182
po_zh_8342_05,0.0000,0.0284,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0000,0.0114,...,0.0000,0.0255,0.0296,0.0150,0.0212,0.0152,0.0120,0.0210,1.0000,0.0091
po_zh_8342_06,0.0000,0.0000,0.0,0.0,0.0000,0.0546,0.0000,0.0,0.0000,0.0152,...,0.0000,0.0122,0.0496,0.0810,0.1197,0.0127,0.0078,0.0182,0.0091,1.0000

======================================================================
Pairwise Cosine Similarity
======================================================================

,event_id_1,event_name_1,event_id_2,event_name_2,cosine_similarity
0,SPSP192506121501_01,天津扶輪社電上海扶輪社日前接天津扶輪社來電略謂天津扶輪社同人敬以同氣之誼致候上海扶輪社諸君並...,SPSP193109022001_01,扶輪社明日聚餐會上海扶輪社本星期四午間十二時三十分、在老卡爾登舉行聚餐會,0.2956
1,po_zh_8342_03,隨著「第二高速公路」於今年1月全線通車,po_zh_8342_04,十二條「東西向快速道路」、「西濱快速公路」，以及「高速鐵路」於明年十月開始營運通車,0.2624
2,po_zh_8342_00,陳總統水扁先生今天下午前往南投縣埔里鎮參加國道六號南投段開工動土典禮，並應邀致詞。,po_zh_8342_01,今天阿扁非常高興到南投埔里，來參加「新十大建設」在中部地區最重大工程之一：「國道六號南投段」...,0.2570
3,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,0.1534
4,INSCR-KR4d0232-WYG-f006-0002_01,始作浮梁,INSCR-KR4d0466-WYG-f011-0010_03,始事,0.1211
...,...,...,...,...,...
226,SPSP192506121501_02,該社當即擬覆略謂敬問起居卓見深合私衷同人等正盡力重建相尊相信之原則,po_zh_8342_00,陳總統水扁先生今天下午前往南投縣埔里鎮參加國道六號南投段開工動土典禮，並應邀致詞。,0.0000
227,SPSP192506121501_02,該社當即擬覆略謂敬問起居卓見深合私衷同人等正盡力重建相尊相信之原則,po_zh_8342_05,過去半年以來，股市與房市不斷加溫,0.0000
228,SPSP193109022001_01,扶輪社明日聚餐會上海扶輪社本星期四午間十二時三十分、在老卡爾登舉行聚餐會,SPSP193109022001_02,請安德魯博士演講最近探險蒙古沙漠情形,0.0000
229,SPSP192506121501_02,該社當即擬覆略謂敬問起居卓見深合私衷同人等正盡力重建相尊相信之原則,po_zh_8342_06,在開工今天，祝福我們國道工程一切順利,0.0000
230,SPSP193109022001_01,扶輪社明日聚餐會上海扶輪社本星期四午間十二時三十分、在老卡爾登舉行聚餐會,po_zh_8342_02,當年政府開發中部橫貫公路,0.0000

======================================================================
完成
======================================================================

Event data： /content/chinese_event_events.csv
Event mapping： /content/chinese_event_mapping.csv
Similarity matrix： /content/chinese_event_cosine_similarity_matrix.csv
Pairwise results： /content/chinese_event_cosine_similarity_pairwise.csv

## English

In [16]:
# ============================================================
# English Event Name Cosine Similarity
# 保留 event_id
# ============================================================

import os
import json
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# ============================================================
# 1. 指定英文 JSON 檔案
# ============================================================

folder_path = "/content/"

json_files = [
    "annotations_enc_rotary_en_1319843498.json",
    "annotations_enc_rotary_en_1319854677.json",
    "po_en_1.json",
    "po_en_1669.json"
]


# ============================================================
# 2. 讀取 JSON
# ============================================================

events = []

for filename in json_files:

    file_path = os.path.join(folder_path, filename)

    if not os.path.exists(file_path):
        print(f"⚠ 找不到檔案：{filename}")
        continue

    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # --------------------------------------------------------
    # JSON 最外層可能是：
    #
    # "ENC/rotary/eng"
    #
    # 或其他 document key
    # --------------------------------------------------------

    for document_key, document_data in data.items():

        if not isinstance(document_data, dict):
            continue

        event_list = document_data.get("events", [])

        for event in event_list:

            event_id = event.get("event_id")
            event_name = event.get("event_name")

            if event_name is None:
                continue

            event_name = str(event_name).strip()

            if event_name == "":
                continue

            events.append({
                "event_id": event_id,
                "event_name": event_name,
                "source_file": filename,
                "document_key": document_key
            })


# ============================================================
# 3. 建立原始 Event DataFrame
# ============================================================

events_df = pd.DataFrame(events)

print("=" * 70)
print("資料讀取結果")
print("=" * 70)

print(f"JSON 檔案數：{len(json_files)}")
print(f"Event 總數：{len(events_df)}")

if len(events_df) > 0:

    print(
        f"不同 event_name 數："
        f"{events_df['event_name'].nunique()}"
    )

    print("\n各檔案 Event 數量：")
    print(
        events_df["source_file"]
        .value_counts()
    )


# ============================================================
# 4. 保留 event_id 的 Unique Event
#
# 注意：
# 同一 event_name 如果對應不同 event_id，
# 這裡仍然會保留不同 event。
#
# 只有 event_id + event_name 完全相同時才去除重複。
# ============================================================

unique_events_df = (
    events_df[
        [
            "event_id",
            "event_name",
            "source_file",
            "document_key"
        ]
    ]
    .drop_duplicates(
        subset=["event_id", "event_name"]
    )
    .reset_index(drop=True)
)


print("\n" + "=" * 70)
print("Unique Events")
print("=" * 70)

print(
    f"Unique Event 數："
    f"{len(unique_events_df)}"
)

display(unique_events_df)


# ============================================================
# 5. TF-IDF
# ============================================================

vectorizer = TfidfVectorizer(
    analyzer="word",
    ngram_range=(1, 2),
    lowercase=True,
    stop_words="english",
    min_df=1
)

tfidf_matrix = vectorizer.fit_transform(
    unique_events_df["event_name"]
)


print("\n" + "=" * 70)
print("TF-IDF")
print("=" * 70)

print(
    f"TF-IDF Matrix Shape："
    f"{tfidf_matrix.shape}"
)


# ============================================================
# 6. Cosine Similarity
# ============================================================

similarity_matrix = cosine_similarity(
    tfidf_matrix
)


# ============================================================
# 7. 建立 Pairwise Similarity
#
# CSV 會保留：
#
# event_id_1
# event_name_1
# event_id_2
# event_name_2
# cosine_similarity
# ============================================================

pairwise_results = []

n_events = len(unique_events_df)

for i in range(n_events):

    for j in range(i + 1, n_events):

        pairwise_results.append({

            "event_id_1":
                unique_events_df.loc[i, "event_id"],

            "event_name_1":
                unique_events_df.loc[i, "event_name"],

            "event_id_2":
                unique_events_df.loc[j, "event_id"],

            "event_name_2":
                unique_events_df.loc[j, "event_name"],

            "cosine_similarity":
                similarity_matrix[i, j]
        })


pairwise_df = pd.DataFrame(
    pairwise_results
)


# ============================================================
# 8. 由高到低排序
# ============================================================

pairwise_df = (
    pairwise_df
    .sort_values(
        "cosine_similarity",
        ascending=False
    )
    .reset_index(drop=True)
)


# ============================================================
# 9. 顯示最高相似度
# ============================================================

print("\n" + "=" * 70)
print("Top 30 Most Similar Event Pairs")
print("=" * 70)

display(
    pairwise_df
    .head(30)
    .round(4)
)


# ============================================================
# 10. 建立完整 Similarity Matrix
#
# index / columns 使用 event_id
# ============================================================

similarity_df = pd.DataFrame(
    similarity_matrix,
    index=unique_events_df["event_id"],
    columns=unique_events_df["event_id"]
)


print("\n" + "=" * 70)
print("Cosine Similarity Matrix")
print("=" * 70)

display(
    similarity_df.round(4)
)


# ============================================================
# 11. 建立 Event 對照表
#
# event_id → event_name
# ============================================================

event_mapping_df = unique_events_df[
    [
        "event_id",
        "event_name",
        "source_file",
        "document_key"
    ]
].copy()


# ============================================================
# 12. 儲存 CSV
# ============================================================

events_output = (
    "/content/english_events.csv"
)

mapping_output = (
    "/content/english_event_mapping.csv"
)

matrix_output = (
    "/content/english_event_cosine_similarity_matrix.csv"
)

pairwise_output = (
    "/content/english_event_cosine_similarity_pairwise.csv"
)


# 原始 Event
events_df.to_csv(
    events_output,
    index=False,
    encoding="utf-8-sig"
)


# Event ID 對照表
event_mapping_df.to_csv(
    mapping_output,
    index=False,
    encoding="utf-8-sig"
)


# Similarity Matrix
similarity_df.to_csv(
    matrix_output,
    encoding="utf-8-sig"
)


# Pairwise Similarity
pairwise_df.to_csv(
    pairwise_output,
    index=False,
    encoding="utf-8-sig"
)


# ============================================================
# 13. 完成
# ============================================================

print("\n" + "=" * 70)
print("完成")
print("=" * 70)

print(f"✓ 原始 Event CSV：")
print(f"  {events_output}")

print(f"\n✓ Event ID 對照表：")
print(f"  {mapping_output}")

print(f"\n✓ Cosine Similarity Matrix：")
print(f"  {matrix_output}")

print(f"\n✓ Pairwise Cosine Similarity：")
print(f"  {pairwise_output}")

======================================================================
資料讀取結果
======================================================================
JSON 檔案數：4
Event 總數：37
不同 event_name 數：36

各檔案 Event 數量：
source_file
annotations_enc_rotary_en_1319854677.json    18
annotations_enc_rotary_en_1319843498.json    15
po_en_1.json                                  3
po_en_1669.json                               1
Name: count, dtype: int64

======================================================================
Unique Events
======================================================================
Unique Event 數：37

,event_id,event_name,source_file,document_key
0,1319843498_01,120 women enrolled in a ten-day course of lect...,annotations_enc_rotary_en_1319843498.json,ENC/rotary/eng
1,1319843498_02,Jean Alvalyn born to Mr and Mrs Cannon at Fooc...,annotations_enc_rotary_en_1319843498.json,ENC/rotary/eng
2,1319843498_03,"Social evening, hearts drive and dance at the ...",annotations_enc_rotary_en_1319843498.json,ENC/rotary/eng
3,1319843498_04,Mrs George Fryer at home to friends at No 4 Ed...,annotations_enc_rotary_en_1319843498.json,ENC/rotary/eng
4,1319843498_05,Mrs George Fryer at home to friends at No 4 Ed...,annotations_enc_rotary_en_1319843498.json,ENC/rotary/eng
5,1319843498_06,Marriage of Dr Amy Metcalf and Capt Albert Bow...,annotations_enc_rotary_en_1319843498.json,ENC/rotary/eng
6,1319843498_07,Mrs Bowen left China for France,annotations_enc_rotary_en_1319843498.json,ENC/rotary/eng
7,1319843498_08,Reception for parents given by faculty of the ...,annotations_enc_rotary_en_1319843498.json,ENC/rotary/eng
8,1319843498_09,Wedding of John Bristow and Miss Frances Helen...,annotations_enc_rotary_en_1319843498.json,ENC/rotary/eng
9,1319843498_10,"Couple departed on wedding trip to Chungking, ...",annotations_enc_rotary_en_1319843498.json,ENC/rotary/eng
10,1319843498_11,Armistice celebration at the Shanghai Club,annotations_enc_rotary_en_1319843498.json,ENC/rotary/eng
11,1319843498_12,Guests assembled in the banquet hall for supper,annotations_enc_rotary_en_1319843498.json,ENC/rotary/eng
12,1319843498_13,Vocal solos rendered in the ballroom during th...,annotations_enc_rotary_en_1319843498.json,ENC/rotary/eng
13,1319843498_14,American Woman's Club decides to hold an infor...,annotations_enc_rotary_en_1319843498.json,ENC/rotary/eng
14,1319843498_15,"Dinner given by YangTcheng, Commissioner of Fo...",annotations_enc_rotary_en_1319843498.json,ENC/rotary/eng
15,1319854677_01,Proclamations issued enjoining slaughter of pi...,annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
16,1319854677_03,Peking officials prayed for rain; people ate s...,annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
17,1319854677_04,Bitter opposition raised against the newly pro...,annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
18,1319854677_05,About 180 Peiyang students quartered themselve...,annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
19,1319854677_06,"Liang Tun-yen, former minister of communicatio...",annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
20,1319854677_07,General Li Yuan-hung returned to his Tientsin ...,annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
21,1319854677_08,Presidential mandates appointed Yueh Chao-chu ...,annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
22,1319854677_09,Two main lines of the Peking tramways to begin...,annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
23,1319854677_10,Fliers practising day and night in and around ...,annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
24,1319854677_11,About 200 Chinese held a meeting in Central Pa...,annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
25,1319854677_12,"Burgess, secretary of the Community Service de...",annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
26,1319854677_13,"Dr Jacob Gould Schurman, American Minister to ...",annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
27,1319854677_14,They left for Taian for a sightseeing trip up ...,annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
28,1319854677_15,Mrs Schurman to return to Peking; Dr Schurman ...,annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
29,1319854677_16,"General William Conner, aides, and Mr Peck lef...",annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
30,1319854677_17,"Hiram Cleaver, ex-president of the Continental...",annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
31,1319854677_18,An unidentified messenger brought a package to...,annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
32,1319854677_19,"Dr Koo ordered a package opened, resulting in ...",annotations_enc_rotary_en_1319854677.json,ENC/rotary/eng
33,TW_001,Vice President Vincent C. Siew on the morning ...,po_en_1.json,Taiwan presidential office
34,TW_002,Meeting the delegation at the Presidential Bui...,po_en_1.json,Taiwan presidential office
35,TW_003,"Over the years, the conference has served as a...",po_en_1.json,Taiwan presidential office
36,TW_001,Feb. 25 (CNA) President Chen Shui-bian preside...,po_en_1669.json,Taiwan Presidential office

======================================================================
TF-IDF
======================================================================
TF-IDF Matrix Shape：(37, 547)

======================================================================
Top 30 Most Similar Event Pairs
======================================================================

,event_id_1,event_name_1,event_id_2,event_name_2,cosine_similarity
0,1319843498_04,Mrs George Fryer at home to friends at No 4 Ed...,1319843498_05,Mrs George Fryer at home to friends at No 4 Ed...,1.0000
1,1319854677_13,"Dr Jacob Gould Schurman, American Minister to ...",1319854677_15,Mrs Schurman to return to Peking; Dr Schurman ...,0.2861
2,1319854677_18,An unidentified messenger brought a package to...,1319854677_19,"Dr Koo ordered a package opened, resulting in ...",0.1646
3,TW_001,Vice President Vincent C. Siew on the morning ...,TW_002,Meeting the delegation at the Presidential Bui...,0.1443
4,1319843498_06,Marriage of Dr Amy Metcalf and Capt Albert Bow...,1319843498_07,Mrs Bowen left China for France,0.1415
5,1319843498_07,Mrs Bowen left China for France,1319854677_13,"Dr Jacob Gould Schurman, American Minister to ...",0.1334
6,1319843498_10,"Couple departed on wedding trip to Chungking, ...",1319854677_15,Mrs Schurman to return to Peking; Dr Schurman ...,0.1175
7,1319843498_02,Jean Alvalyn born to Mr and Mrs Cannon at Fooc...,1319843498_07,Mrs Bowen left China for France,0.1017
8,1319854677_12,"Burgess, secretary of the Community Service de...",1319854677_13,"Dr Jacob Gould Schurman, American Minister to ...",0.0872
9,1319843498_12,Guests assembled in the banquet hall for supper,1319843498_13,Vocal solos rendered in the ballroom during th...,0.0835
10,1319843498_14,American Woman's Club decides to hold an infor...,1319843498_15,"Dinner given by YangTcheng, Commissioner of Fo...",0.0831
11,1319843498_01,120 women enrolled in a ten-day course of lect...,1319854677_10,Fliers practising day and night in and around ...,0.0809
12,1319854677_12,"Burgess, secretary of the Community Service de...",1319854677_16,"General William Conner, aides, and Mr Peck lef...",0.0730
13,1319854677_07,General Li Yuan-hung returned to his Tientsin ...,1319854677_16,"General William Conner, aides, and Mr Peck lef...",0.0729
14,1319854677_13,"Dr Jacob Gould Schurman, American Minister to ...",1319854677_16,"General William Conner, aides, and Mr Peck lef...",0.0691
15,1319854677_06,"Liang Tun-yen, former minister of communicatio...",1319854677_08,Presidential mandates appointed Yueh Chao-chu ...,0.0679
16,1319843498_02,Jean Alvalyn born to Mr and Mrs Cannon at Fooc...,1319854677_13,"Dr Jacob Gould Schurman, American Minister to ...",0.0633
17,1319854677_08,Presidential mandates appointed Yueh Chao-chu ...,1319854677_13,"Dr Jacob Gould Schurman, American Minister to ...",0.0626
18,1319843498_08,Reception for parents given by faculty of the ...,1319843498_15,"Dinner given by YangTcheng, Commissioner of Fo...",0.0622
19,1319843498_10,"Couple departed on wedding trip to Chungking, ...",1319854677_14,They left for Taian for a sightseeing trip up ...,0.0617
20,1319854677_11,About 200 Chinese held a meeting in Central Pa...,TW_002,Meeting the delegation at the Presidential Bui...,0.0614
21,1319854677_06,"Liang Tun-yen, former minister of communicatio...",1319854677_13,"Dr Jacob Gould Schurman, American Minister to ...",0.0589
22,1319843498_11,Armistice celebration at the Shanghai Club,1319843498_15,"Dinner given by YangTcheng, Commissioner of Fo...",0.0570
23,1319843498_03,"Social evening, hearts drive and dance at the ...",1319843498_11,Armistice celebration at the Shanghai Club,0.0566
24,1319843498_07,Mrs Bowen left China for France,1319854677_14,They left for Taian for a sightseeing trip up ...,0.0555
25,1319854677_12,"Burgess, secretary of the Community Service de...",1319854677_15,Mrs Schurman to return to Peking; Dr Schurman ...,0.0554
26,1319854677_12,"Burgess, secretary of the Community Service de...",1319854677_17,"Hiram Cleaver, ex-president of the Continental...",0.0553
27,1319843498_07,Mrs Bowen left China for France,1319843498_09,Wedding of John Bristow and Miss Frances Helen...,0.0545
28,1319843498_09,Wedding of John Bristow and Miss Frances Helen...,1319843498_10,"Couple departed on wedding trip to Chungking, ...",0.0535
29,1319843498_12,Guests assembled in the banquet hall for supper,1319854677_16,"General William Conner, aides, and Mr Peck lef...",0.0534

======================================================================
Cosine Similarity Matrix
======================================================================

event_id,1319843498_01,1319843498_02,1319843498_03,1319843498_04,1319843498_05,1319843498_06,1319843498_07,1319843498_08,1319843498_09,1319843498_10,...,1319854677_14,1319854677_15,1319854677_16,1319854677_17,1319854677_18,1319854677_19,TW_001,TW_002,TW_003,TW_001
event_id,,,,,,,,,,,,,,,,,,,,,
1319843498_01,1.0000,0.0000,0.0000,0.0327,0.0327,0.0000,0.0000,0.0318,0.0000,0.0295,...,0.0000,0.0240,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319843498_02,0.0000,1.0000,0.0000,0.0337,0.0337,0.0000,0.1017,0.0000,0.0392,0.0000,...,0.0000,0.0248,0.0422,0.0226,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319843498_03,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319843498_04,0.0327,0.0337,0.0000,1.0000,1.0000,0.0000,0.0469,0.0331,0.0000,0.0307,...,0.0000,0.0524,0.0000,0.0250,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319843498_05,0.0327,0.0337,0.0000,1.0000,1.0000,0.0000,0.0469,0.0331,0.0000,0.0307,...,0.0000,0.0524,0.0000,0.0250,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319843498_06,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.1415,0.0000,0.0000,0.0000,...,0.0000,0.0268,0.0000,0.0000,0.0329,0.0351,0.0000,0.0000,0.0000,0.0000
1319843498_07,0.0000,0.1017,0.0000,0.0469,0.0469,0.1415,1.0000,0.0000,0.0545,0.0000,...,0.0555,0.0345,0.0379,0.0314,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319843498_08,0.0318,0.0000,0.0000,0.0331,0.0331,0.0000,0.0000,1.0000,0.0000,0.0299,...,0.0000,0.0243,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319843498_09,0.0000,0.0392,0.0000,0.0000,0.0000,0.0000,0.0545,0.0000,1.0000,0.0535,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319843498_10,0.0295,0.0000,0.0000,0.0307,0.0307,0.0000,0.0000,0.0299,0.0535,1.0000,...,0.0617,0.1175,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319843498_11,0.0451,0.0000,0.0566,0.0469,0.0469,0.0000,0.0000,0.0457,0.0000,0.0424,...,0.0000,0.0345,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319843498_12,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0534,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319843498_13,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319843498_14,0.0000,0.0000,0.0324,0.0000,0.0000,0.0000,0.0000,0.0465,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319843498_15,0.0000,0.0000,0.0366,0.0000,0.0000,0.0000,0.0000,0.0622,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319854677_01,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319854677_03,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0352,0.0156,0.0160,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319854677_04,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319854677_05,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319854677_06,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0357,0.0159,0.0162,0.0462,0.0000,0.0000,0.0000,0.0000,0.0000
1319854677_07,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0729,0.0000,0.0425,0.0000,0.0000,0.0000,0.0000,0.0000
1319854677_08,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0317,0.0000,0.0000
1319854677_09,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0439,0.0195,0.0200,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319854677_10,0.0809,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0495,0.0220,0.0226,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319854677_11,0.0000,0.0000,0.0263,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0270,0.0120,0.0123,0.0000,0.0000,0.0000,0.0614,0.0000,0.0237
1319854677_12,0.0270,0.0000,0.0523,0.0281,0.0281,0.0000,0.0479,0.0273,0.0000,0.0254,...,0.0365,0.0554,0.0730,0.0553,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319854677_13,0.0000,0.0633,0.0000,0.0292,0.0292,0.0285,0.1334,0.0459,0.0339,0.0000,...,0.0345,0.2861,0.0691,0.0345,0.0326,0.0348,0.0000,0.0000,0.0000,0.0000
1319854677_14,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0555,0.0000,0.0000,0.0617,...,1.0000,0.0000,0.0289,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319854677_15,0.0240,0.0248,0.0000,0.0524,0.0524,0.0268,0.0345,0.0243,0.0000,0.1175,...,0.0000,1.0000,0.0275,0.0465,0.0307,0.0327,0.0000,0.0000,0.0000,0.0000
1319854677_16,0.0000,0.0422,0.0000,0.0000,0.0000,0.0000,0.0379,0.0000,0.0000,0.0000,...,0.0289,0.0275,1.0000,0.0125,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1319854677_17,0.0000,0.0226,0.0000,0.0250,0.0250,0.0000,0.0314,0.0000,0.0000,0.0000,...,0.0000,0.0465,0.0125,1.0000,0.0000,0.0000,0.0224,0.0234,0.0000,0.0181
1319854677_18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0329,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0307,0.0000,0.0000,1.0000,0.1646,0.0000,0.0000,0.0000,0.0000
1319854677_19,0.0000,0.0000,0.0000,0.0000,0.0000,0.0351,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0327,0.0000,0.0000,0.1646,1.0000,0.0000,0.0000,0.0000,0.0000
TW_001,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0224,0.0000,0.0000,1.0000,0.1443,0.0374,0.0172
TW_002,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0234,0.0000,0.0000,0.1443,1.0000,0.0000,0.0180
TW_003,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0374,0.0000,1.0000,0.0000
TW_001,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0181,0.0000,0.0000,0.0172,0.0180,0.0000,1.0000

======================================================================
完成
======================================================================
✓ 原始 Event CSV：
  /content/english_events.csv

✓ Event ID 對照表：
  /content/english_event_mapping.csv

✓ Cosine Similarity Matrix：
  /content/english_event_cosine_similarity_matrix.csv

✓ Pairwise Cosine Similarity：
  /content/english_event_cosine_similarity_pairwise.csv

## Annotations v.s. LLM

In [18]:
# ==========================================================
# Event Name Cosine Similarity
#
# 比較：
# 1. 中、英文 JSON 檔案中的 event_name
# 2. extraction_events_final_schema.json 中的 event_name
#
# 方法：
# TF-IDF Character N-gram
# Cosine Similarity
#
# 保留：
# source_event_id
# source_event_name
# schema_event_id
# schema_event_name
# ==========================================================

import os
import json
import glob
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# ==========================================================
# 1. Settings
# ==========================================================

folder_path = "/content/"

# Schema file
schema_path = (
    "/content/extraction_events_final_schema.json"
)

# Character N-gram
#
# 可以同時處理：
# 中文：
#   橋燬
#   橋落成
#
# 英文：
#   Bridge was destroyed
#   Construction of the bridge
#
# 中英混合：
#   Bridge construction 造橋
#
NGRAM_RANGE = (1, 3)


# ==========================================================
# 2. Read source JSON files
#
# 排除 extraction_events_final_schema.json
# ==========================================================

json_files = sorted(
    [
        f
        for f in glob.glob(
            os.path.join(
                folder_path,
                "*.json"
            )
        )
        if os.path.abspath(f)
        != os.path.abspath(schema_path)
    ]
)


print("=" * 70)
print("Source JSON files")
print("=" * 70)

print(
    f"找到 {len(json_files)} 個來源 JSON 檔案"
)

for file_path in json_files:
    print(
        " -",
        os.path.basename(file_path)
    )


# ==========================================================
# 3. Extract events from source JSON files
#
# 支援：
#
# 中文 JSON：
# {
#     "topic_record": {
#         "events": [...]
#     }
# }
#
# 英文 JSON：
# {
#     "ENC/rotary/eng": {
#         "events": [...]
#     }
# }
# ==========================================================

source_events = []


for file_path in json_files:

    file_name = os.path.basename(
        file_path
    )

    with open(
        file_path,
        "r",
        encoding="utf-8"
    ) as f:

        data = json.load(f)


    file_event_count = 0


    # ------------------------------------------------------
    # Case 1
    # topic_record -> events
    # ------------------------------------------------------

    if isinstance(data, dict):

        topic_record = data.get(
            "topic_record"
        )

        if isinstance(
            topic_record,
            dict
        ):

            event_list = (
                topic_record.get(
                    "events",
                    []
                )
            )

            for event in event_list:

                if not isinstance(
                    event,
                    dict
                ):
                    continue

                event_id = event.get(
                    "event_id"
                )

                event_name = event.get(
                    "event_name"
                )

                if event_name is None:
                    continue

                event_name = str(
                    event_name
                ).strip()

                if event_name == "":
                    continue

                source_events.append({

                    "source_event_id":
                        event_id,

                    "source_event_name":
                        event_name,

                    "source_file":
                        file_name

                })

                file_event_count += 1


    # ------------------------------------------------------
    # Case 2
    # 其他最外層 key -> events
    #
    # 例如：
    #
    # "ENC/rotary/eng": {
    #     "events": [...]
    # }
    # ------------------------------------------------------

    if isinstance(data, dict):

        for document_key, document_data in data.items():

            # topic_record 已經處理
            if document_key == "topic_record":
                continue

            if not isinstance(
                document_data,
                dict
            ):
                continue

            event_list = (
                document_data.get(
                    "events"
                )
            )

            if not isinstance(
                event_list,
                list
            ):
                continue


            for event in event_list:

                if not isinstance(
                    event,
                    dict
                ):
                    continue

                event_id = event.get(
                    "event_id"
                )

                event_name = event.get(
                    "event_name"
                )

                if event_name is None:
                    continue

                event_name = str(
                    event_name
                ).strip()

                if event_name == "":
                    continue

                source_events.append({

                    "source_event_id":
                        event_id,

                    "source_event_name":
                        event_name,

                    "source_file":
                        file_name

                })

                file_event_count += 1


    print(
        f"{file_name}: "
        f"{file_event_count} events"
    )


# ==========================================================
# 4. Source Event DataFrame
# ==========================================================

source_df = pd.DataFrame(
    source_events
)


print("\n" + "=" * 70)
print("Source Event Data")
print("=" * 70)

print(
    f"來源 Event 總數："
    f"{len(source_df):,}"
)

print(
    f"不同 source event_id："
    f"{source_df['source_event_id'].nunique():,}"
)

print(
    f"不同 source event_name："
    f"{source_df['source_event_name'].nunique():,}"
)

display(
    source_df.head(20)
)


# ==========================================================
# 5. Read extraction_events_final_schema.json
# ==========================================================

print("\n" + "=" * 70)
print("Reading extraction_events_final_schema.json")
print("=" * 70)


with open(
    schema_path,
    "r",
    encoding="utf-8"
) as f:

    schema_data = json.load(f)


schema_events = schema_data.get(
    "events",
    []
)


print(
    f"Schema Event 總數："
    f"{len(schema_events):,}"
)


# ==========================================================
# 6. Extract Schema Events
# ==========================================================

schema_event_records = []


for event in schema_events:

    if not isinstance(
        event,
        dict
    ):
        continue

    event_id = event.get(
        "event_id"
    )

    event_name = event.get(
        "event_name"
    )

    if event_name is None:
        continue

    event_name = str(
        event_name
    ).strip()

    if event_name == "":
        continue

    schema_event_records.append({

        "schema_event_id":
            event_id,

        "schema_event_name":
            event_name

    })


schema_df = pd.DataFrame(
    schema_event_records
)


print(
    f"有效 Schema Event："
    f"{len(schema_df):,}"
)

print(
    f"不同 schema event_id："
    f"{schema_df['schema_event_id'].nunique():,}"
)

print(
    f"不同 schema event_name："
    f"{schema_df['schema_event_name'].nunique():,}"
)


display(
    schema_df.head(20)
)


# ==========================================================
# 7. TF-IDF
#
# 重要：
#
# source event + schema event
# 一起建立 TF-IDF vocabulary
#
# 這樣兩邊會使用同一個向量空間。
# ==========================================================

all_event_names = pd.concat(
    [
        source_df[
            "source_event_name"
        ],
        schema_df[
            "schema_event_name"
        ]
    ],
    ignore_index=True
)


vectorizer = TfidfVectorizer(

    # Character-level
    analyzer="char",

    # Chinese / English 都可以
    ngram_range=NGRAM_RANGE,

    # 英文大小寫不區分
    lowercase=True,

    min_df=1
)


tfidf_all = vectorizer.fit_transform(
    all_event_names
)


# ==========================================================
# 8. Separate source / schema vectors
# ==========================================================

source_count = len(
    source_df
)

schema_count = len(
    schema_df
)


source_tfidf = (
    tfidf_all[
        :source_count
    ]
)


schema_tfidf = (
    tfidf_all[
        source_count:
    ]
)


print("\n" + "=" * 70)
print("TF-IDF")
print("=" * 70)

print(
    "Source TF-IDF shape:",
    source_tfidf.shape
)

print(
    "Schema TF-IDF shape:",
    schema_tfidf.shape
)


# ==========================================================
# 9. Cosine Similarity
#
# 每一個 source event
# 對每一個 schema event
#
# 例如：
#
# source_event_1
#       ↓
# schema_event_1
# schema_event_2
# schema_event_3
# ...
#
# source_event_2
#       ↓
# schema_event_1
# schema_event_2
# ...
# ==========================================================

similarity_matrix = cosine_similarity(
    source_tfidf,
    schema_tfidf
)


print("\n" + "=" * 70)
print("Cosine Similarity")
print("=" * 70)

print(
    "Similarity matrix shape:",
    similarity_matrix.shape
)


# ==========================================================
# 10. 建立 Pairwise Results
#
# 保留雙方 event_id
# ==========================================================

pairwise_results = []


for i in range(
    source_count
):

    for j in range(
        schema_count
    ):

        pairwise_results.append({

            "source_event_id":
                source_df.iloc[
                    i
                ]["source_event_id"],

            "source_event_name":
                source_df.iloc[
                    i
                ]["source_event_name"],

            "source_file":
                source_df.iloc[
                    i
                ]["source_file"],

            "schema_event_id":
                schema_df.iloc[
                    j
                ]["schema_event_id"],

            "schema_event_name":
                schema_df.iloc[
                    j
                ]["schema_event_name"],

            "cosine_similarity":
                similarity_matrix[
                    i,
                    j
                ]

        })


pairwise_df = pd.DataFrame(
    pairwise_results
)


# ==========================================================
# 11. Sort by similarity
# ==========================================================

pairwise_df = (
    pairwise_df
    .sort_values(
        "cosine_similarity",
        ascending=False
    )
    .reset_index(drop=True)
)


# ==========================================================
# 12. Display Top 50
# ==========================================================

print("\n" + "=" * 70)
print("Top 50 Similar Event Pairs")
print("=" * 70)

display(
    pairwise_df
    .head(50)
    .round(4)
)


# ==========================================================
# 13. 每個 Source Event 找最高相似的 Schema Event
#
# 這個結果通常比完整 pairwise 更適合後續人工檢查。
# ==========================================================

best_match_df = (
    pairwise_df
    .sort_values(
        "cosine_similarity",
        ascending=False
    )
    .drop_duplicates(
        subset=[
            "source_event_id"
        ]
    )
    .sort_values(
        "source_event_id"
    )
    .reset_index(drop=True)
)


print("\n" + "=" * 70)
print("Best Schema Match for Each Source Event")
print("=" * 70)

display(
    best_match_df
)


# ==========================================================
# 14. Save source events
# ==========================================================

source_output = (
    "/content/"
    "source_events_with_event_id.csv"
)


source_df.to_csv(
    source_output,
    index=False,
    encoding="utf-8-sig"
)


# ==========================================================
# 15. Save schema events
# ==========================================================

schema_output = (
    "/content/"
    "schema_events_with_event_id.csv"
)


schema_df.to_csv(
    schema_output,
    index=False,
    encoding="utf-8-sig"
)


# ==========================================================
# 16. Save complete pairwise similarity
# ==========================================================

pairwise_output = (
    "/content/"
    "source_vs_schema_event_cosine_similarity.csv"
)


pairwise_df.to_csv(
    pairwise_output,
    index=False,
    encoding="utf-8-sig"
)


# ==========================================================
# 17. Save best match
# ==========================================================

best_match_output = (
    "/content/"
    "source_vs_schema_best_event_match.csv"
)


best_match_df.to_csv(
    best_match_output,
    index=False,
    encoding="utf-8-sig"
)


# ==========================================================
# 18. 完成
# ==========================================================

print("\n" + "=" * 70)
print("完成")
print("=" * 70)

print(
    "\nSource Events："
)

print(
    source_output
)

print(
    "\nSchema Events："
)

print(
    schema_output
)

print(
    "\nComplete Pairwise Similarity："
)

print(
    pairwise_output
)

print(
    "\nBest Match："
)

print(
    best_match_output
)

======================================================================
Source JSON files
======================================================================
找到 10 個來源 JSON 檔案
 - INSCR-KR4d0232-WYG-f006-0002.json
 - INSCR-KR4d0466-WYG-f011-0010.json
 - annotations_enc_rotary_cmn_SPSP192506121501.json
 - annotations_enc_rotary_cmn_SPSP193109022001.json
 - annotations_enc_rotary_en_1319843498.json
 - annotations_enc_rotary_en_1319854677.json
 - po_en_1.json
 - po_en_1669.json
 - structure_example_TW_po_zh_2376.json
 - structure_example_TW_po_zh_8342_ZC.json
INSCR-KR4d0232-WYG-f006-0002.json: 4 events
INSCR-KR4d0466-WYG-f011-0010.json: 5 events
annotations_enc_rotary_cmn_SPSP192506121501.json: 2 events
annotations_enc_rotary_cmn_SPSP193109022001.json: 2 events
annotations_enc_rotary_en_1319843498.json: 15 events
annotations_enc_rotary_en_1319854677.json: 18 events
po_en_1.json: 3 events
po_en_1669.json: 1 events
structure_example_TW_po_zh_2376.json: 2 events
structure_example_TW_po_zh_8342_ZC.json: 7 events

======================================================================
Source Event Data
======================================================================
來源 Event 總數：59
不同 source event_id：58
不同 source event_name：58

,source_event_id,source_event_name,source_file
0,INSCR-KR4d0232-WYG-f006-0002_01,始作浮梁,INSCR-KR4d0232-WYG-f006-0002.json
1,INSCR-KR4d0232-WYG-f006-0002_02,漂航斷笮／橋毁,INSCR-KR4d0232-WYG-f006-0002.json
2,INSCR-KR4d0232-WYG-f006-0002_03,造端,INSCR-KR4d0232-WYG-f006-0002.json
3,INSCR-KR4d0232-WYG-f006-0002_04,告具,INSCR-KR4d0232-WYG-f006-0002.json
4,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,INSCR-KR4d0466-WYG-f011-0010.json
5,INSCR-KR4d0466-WYG-f011-0010_02,度材鳩工,INSCR-KR4d0466-WYG-f011-0010.json
6,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json
7,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json
8,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,INSCR-KR4d0466-WYG-f011-0010.json
9,SPSP192506121501_01,天津扶輪社電上海扶輪社日前接天津扶輪社來電略謂天津扶輪社同人敬以同氣之誼致候上海扶輪社諸君並...,annotations_enc_rotary_cmn_SPSP192506121501.json
10,SPSP192506121501_02,該社當即擬覆略謂敬問起居卓見深合私衷同人等正盡力重建相尊相信之原則,annotations_enc_rotary_cmn_SPSP192506121501.json
11,SPSP193109022001_01,扶輪社明日聚餐會上海扶輪社本星期四午間十二時三十分、在老卡爾登舉行聚餐會,annotations_enc_rotary_cmn_SPSP193109022001.json
12,SPSP193109022001_02,請安德魯博士演講最近探險蒙古沙漠情形,annotations_enc_rotary_cmn_SPSP193109022001.json
13,1319843498_01,120 women enrolled in a ten-day course of lect...,annotations_enc_rotary_en_1319843498.json
14,1319843498_02,Jean Alvalyn born to Mr and Mrs Cannon at Fooc...,annotations_enc_rotary_en_1319843498.json
15,1319843498_03,"Social evening, hearts drive and dance at the ...",annotations_enc_rotary_en_1319843498.json
16,1319843498_04,Mrs George Fryer at home to friends at No 4 Ed...,annotations_enc_rotary_en_1319843498.json
17,1319843498_05,Mrs George Fryer at home to friends at No 4 Ed...,annotations_enc_rotary_en_1319843498.json
18,1319843498_06,Marriage of Dr Amy Metcalf and Capt Albert Bow...,annotations_enc_rotary_en_1319843498.json
19,1319843498_07,Mrs Bowen left China for France,annotations_enc_rotary_en_1319843498.json

======================================================================
Reading extraction_events_final_schema.json
======================================================================
Schema Event 總數：48
有效 Schema Event：48
不同 schema event_id：48
不同 schema event_name：48

,schema_event_id,schema_event_name
0,po_zh_2376_1,中時晚報及勁報報導總統府公務車撞六車傷五人
1,po_zh_2376_2,台北市羅斯福路發生疑似暴衝之連環車禍
2,po_en_1669_1,President Chen Shui-bian presided over a cerem...
3,SPSP192606271118_1,沈鴻來入美國俄伯靈大學經濟銀行科
4,SPSP192606271118_2,沈鴻來以第一名畢業獲學士位
5,KR4d0466-WYG-f011-0010_1,橋燬
6,KR4d0466-WYG-f011-0010_2,為梁以濟
7,KR4d0466-WYG-f011-0010_3,橋始事
8,KR4d0466-WYG-f011-0010_4,橋落成
9,SPSP192506121501_1,天津扶輪社電上海扶輪社
10,po_en_1_1,Vice President Vincent C. Siew met with the In...
11,KR4d0232-WYG-f006-0002_1,陳侯森始作浮梁
12,KR4d0232-WYG-f006-0002_2,甚雨淫潦漂航斷笮
13,KR4d0232-WYG-f006-0002_3,趙景明復新之橋造端
14,KR4d0232-WYG-f006-0002_4,橋告具
15,1319854677_1,Proclamations were issued enjoining the slaugh...
16,1319854677_2,Bitter opposition has been raised among all cl...
17,1319854677_3,Liang Tun-yen passed away
18,1319854677_4,General Li Yuan-hung returned to his Tientsin ...
19,1319854677_5,By presidential mandates issued Yueh Chao-chu ...

======================================================================
TF-IDF
======================================================================
Source TF-IDF shape: (59, 2983)
Schema TF-IDF shape: (48, 2983)

======================================================================
Cosine Similarity
======================================================================
Similarity matrix shape: (59, 48)

======================================================================
Top 50 Similar Event Pairs
======================================================================

,source_event_id,source_event_name,source_file,schema_event_id,schema_event_name,cosine_similarity
0,1319843498_11,Armistice celebration at the Shanghai Club,annotations_enc_rotary_en_1319843498.json,1319843498_11,Armistice celebration at the Shanghai Club,1.0000
1,1319843498_07,Mrs Bowen left China for France,annotations_enc_rotary_en_1319843498.json,1319843498_6,Mrs Bowen left China for France,1.0000
2,1319854677_07,General Li Yuan-hung returned to his Tientsin ...,annotations_enc_rotary_en_1319854677.json,1319854677_4,General Li Yuan-hung returned to his Tientsin ...,0.9610
3,1319843498_15,"Dinner given by YangTcheng, Commissioner of Fo...",annotations_enc_rotary_en_1319843498.json,1319843498_13,dinner given by YangTcheng Commissioner of For...,0.9603
4,1319854677_08,Presidential mandates appointed Yueh Chao-chu ...,annotations_enc_rotary_en_1319854677.json,1319854677_5,By presidential mandates issued Yueh Chao-chu ...,0.9285
5,1319843498_02,Jean Alvalyn born to Mr and Mrs Cannon at Fooc...,annotations_enc_rotary_en_1319843498.json,1319843498_2,Jean Alvalyn was born to Mr and Mrs Cannon at ...,0.9215
6,1319843498_03,"Social evening, hearts drive and dance at the ...",annotations_enc_rotary_en_1319843498.json,1319843498_3,social evening hearts drive and dance will be ...,0.9056
7,1319843498_09,Wedding of John Bristow and Miss Frances Helen...,annotations_enc_rotary_en_1319843498.json,1319843498_8,wedding took place at Hankow China of John Bri...,0.8960
8,1319854677_01,Proclamations issued enjoining slaughter of pi...,annotations_enc_rotary_en_1319854677.json,1319854677_1,Proclamations were issued enjoining the slaugh...,0.8815
9,1319854677_09,Two main lines of the Peking tramways to begin...,annotations_enc_rotary_en_1319854677.json,1319854677_6,two of the main lines of the Peking tramways w...,0.8704
10,1319854677_04,Bitter opposition raised against the newly pro...,annotations_enc_rotary_en_1319854677.json,1319854677_2,Bitter opposition has been raised among all cl...,0.8457
11,TW_001,Feb. 25 (CNA) President Chen Shui-bian preside...,po_en_1669.json,po_en_1669_1,President Chen Shui-bian presided over a cerem...,0.8449
12,1319843498_06,Marriage of Dr Amy Metcalf and Capt Albert Bow...,annotations_enc_rotary_en_1319843498.json,1319843498_5,announcement is made of the marriage of Dr Amy...,0.8415
13,1319843498_01,120 women enrolled in a ten-day course of lect...,annotations_enc_rotary_en_1319843498.json,1319843498_1,120 women enrolled for ten days course of lect...,0.8083
14,po_zh_8342_00,陳總統水扁先生今天下午前往南投縣埔里鎮參加國道六號南投段開工動土典禮，並應邀致詞。,structure_example_TW_po_zh_8342_ZC.json,po_zh_8342_1,陳總統水扁先生前往南投縣埔里鎮參加國道六號南投段開工動土典禮,0.8050
15,TW_001,Vice President Vincent C. Siew on the morning ...,po_en_1.json,po_en_1_1,Vice President Vincent C. Siew met with the In...,0.7932
16,po_zh_2376_01,今天上午在台北市羅斯福路所發生疑似暴衝之連環車禍,structure_example_TW_po_zh_2376.json,po_zh_2376_2,台北市羅斯福路發生疑似暴衝之連環車禍,0.7921
17,1319854677_16,"General William Conner, aides, and Mr Peck lef...",annotations_enc_rotary_en_1319854677.json,1319854677_10,General William Conner left Peking for Loyang,0.7685
18,SPSP192506121501_01,天津扶輪社電上海扶輪社日前接天津扶輪社來電略謂天津扶輪社同人敬以同氣之誼致候上海扶輪社諸君並...,annotations_enc_rotary_cmn_SPSP192506121501.json,SPSP192506121501_1,天津扶輪社電上海扶輪社,0.7604
19,1319854677_13,"Dr Jacob Gould Schurman, American Minister to ...",annotations_enc_rotary_en_1319854677.json,1319854677_9,Dr Jacob Gould Schurman left Peking for Tientsin,0.7460
20,1319854677_17,"Hiram Cleaver, ex-president of the Continental...",annotations_enc_rotary_en_1319854677.json,1319854677_11,Hiram Cleaver and Mrs Cleaver arrived in Peking,0.7382
21,1319843498_10,"Couple departed on wedding trip to Chungking, ...",annotations_enc_rotary_en_1319843498.json,1319843498_9,They departed on their wedding trip to Chungking,0.7369
22,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_4,橋落成,0.7079
23,INSCR-KR4d0232-WYG-f006-0002_04,告具,INSCR-KR4d0232-WYG-f006-0002.json,KR4d0232-WYG-f006-0002_4,橋告具,0.7079
24,1319843498_08,Reception for parents given by faculty of the ...,annotations_enc_rotary_en_1319843498.json,1319843498_7,reception was given to parents and their frien...,0.7020
25,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_3,橋始事,0.6864
26,TW_002,Meeting the delegation at the Presidential Bui...,po_en_1.json,po_en_1_1,Vice President Vincent C. Siew met with the In...,0.6783
27,INSCR-KR4d0232-WYG-f006-0002_01,始作浮梁,INSCR-KR4d0232-WYG-f006-0002.json,KR4d0232-WYG-f006-0002_1,陳侯森始作浮梁,0.6713
28,1319843498_04,Mrs George Fryer at home to friends at No 4 Ed...,annotations_enc_rotary_en_1319843498.json,1319843498_4,Mrs George Fryer will be at home to her freinds,0.6592
29,1319843498_05,Mrs George Fryer at home to friends at No 4 Ed...,annotations_enc_rotary_en_1319843498.json,1319843498_4,Mrs George Fryer will be at home to her freinds,0.6592
30,1319854677_11,About 200 Chinese held a meeting in Central Pa...,annotations_enc_rotary_en_1319854677.json,1319854677_7,held meeting in the Central Park of Peking,0.6246
31,TW_001,Vice President Vincent C. Siew on the morning ...,po_en_1.json,po_en_1669_1,President Chen Shui-bian presided over a cerem...,0.6022
32,TW_002,Meeting the delegation at the Presidential Bui...,po_en_1.json,po_en_1669_1,President Chen Shui-bian presided over a cerem...,0.5896
33,TW_003,"Over the years, the conference has served as a...",po_en_1.json,1319843498_3,social evening hearts drive and dance will be ...,0.5885
34,po_zh_8342_03,隨著「第二高速公路」於今年1月全線通車,structure_example_TW_po_zh_8342_ZC.json,po_zh_8342_2,第二高速公路全線通車,0.5813
35,1319843498_10,"Couple departed on wedding trip to Chungking, ...",annotations_enc_rotary_en_1319843498.json,1319843498_10,returning in December to Shanghai,0.5559
36,SPSP193109022001_01,扶輪社明日聚餐會上海扶輪社本星期四午間十二時三十分、在老卡爾登舉行聚餐會,annotations_enc_rotary_cmn_SPSP193109022001.json,SPSP193109022001_1,上海扶輪社舉行聚餐會,0.5549
37,1319854677_12,"Burgess, secretary of the Community Service de...",annotations_enc_rotary_en_1319854677.json,po_en_1669_1,President Chen Shui-bian presided over a cerem...,0.5451
38,TW_001,Vice President Vincent C. Siew on the morning ...,po_en_1.json,1319854677_6,two of the main lines of the Peking tramways w...,0.5419
39,1319854677_17,"Hiram Cleaver, ex-president of the Continental...",annotations_enc_rotary_en_1319854677.json,po_en_1669_1,President Chen Shui-bian presided over a cerem...,0.5409
40,TW_002,Meeting the delegation at the Presidential Bui...,po_en_1.json,1319854677_6,two of the main lines of the Peking tramways w...,0.5406
41,TW_003,"Over the years, the conference has served as a...",po_en_1.json,po_en_1669_1,President Chen Shui-bian presided over a cerem...,0.5348
42,TW_003,"Over the years, the conference has served as a...",po_en_1.json,1319854677_5,By presidential mandates issued Yueh Chao-chu ...,0.5313
43,1319854677_15,Mrs Schurman to return to Peking; Dr Schurman ...,annotations_enc_rotary_en_1319854677.json,1319843498_10,returning in December to Shanghai,0.5296
44,TW_003,"Over the years, the conference has served as a...",po_en_1.json,1319843498_7,reception was given to parents and their frien...,0.5289
45,1319854677_06,"Liang Tun-yen, former minister of communicatio...",annotations_enc_rotary_en_1319854677.json,po_en_1669_1,President Chen Shui-bian presided over a cerem...,0.5252
46,TW_001,Feb. 25 (CNA) President Chen Shui-bian preside...,po_en_1669.json,po_en_1_1,Vice President Vincent C. Siew met with the In...,0.5247
47,TW_002,Meeting the delegation at the Presidential Bui...,po_en_1.json,1319854677_7,held meeting in the Central Park of Peking,0.5243
48,1319854677_11,About 200 Chinese held a meeting in Central Pa...,annotations_enc_rotary_en_1319854677.json,1319854677_2,Bitter opposition has been raised among all cl...,0.5221
49,TW_002,Meeting the delegation at the Presidential Bui...,po_en_1.json,1319854677_2,Bitter opposition has been raised among all cl...,0.5220

======================================================================
Best Schema Match for Each Source Event
======================================================================

,source_event_id,source_event_name,source_file,schema_event_id,schema_event_name,cosine_similarity
0,1319843498_01,120 women enrolled in a ten-day course of lect...,annotations_enc_rotary_en_1319843498.json,1319843498_1,120 women enrolled for ten days course of lect...,0.808312
1,1319843498_02,Jean Alvalyn born to Mr and Mrs Cannon at Fooc...,annotations_enc_rotary_en_1319843498.json,1319843498_2,Jean Alvalyn was born to Mr and Mrs Cannon at ...,0.921457
2,1319843498_03,"Social evening, hearts drive and dance at the ...",annotations_enc_rotary_en_1319843498.json,1319843498_3,social evening hearts drive and dance will be ...,0.905611
3,1319843498_04,Mrs George Fryer at home to friends at No 4 Ed...,annotations_enc_rotary_en_1319843498.json,1319843498_4,Mrs George Fryer will be at home to her freinds,0.659179
4,1319843498_05,Mrs George Fryer at home to friends at No 4 Ed...,annotations_enc_rotary_en_1319843498.json,1319843498_4,Mrs George Fryer will be at home to her freinds,0.659179
5,1319843498_06,Marriage of Dr Amy Metcalf and Capt Albert Bow...,annotations_enc_rotary_en_1319843498.json,1319843498_5,announcement is made of the marriage of Dr Amy...,0.841518
6,1319843498_07,Mrs Bowen left China for France,annotations_enc_rotary_en_1319843498.json,1319843498_6,Mrs Bowen left China for France,1.000000
7,1319843498_08,Reception for parents given by faculty of the ...,annotations_enc_rotary_en_1319843498.json,1319843498_7,reception was given to parents and their frien...,0.701987
8,1319843498_09,Wedding of John Bristow and Miss Frances Helen...,annotations_enc_rotary_en_1319843498.json,1319843498_8,wedding took place at Hankow China of John Bri...,0.895956
9,1319843498_10,"Couple departed on wedding trip to Chungking, ...",annotations_enc_rotary_en_1319843498.json,1319843498_9,They departed on their wedding trip to Chungking,0.736881
10,1319843498_11,Armistice celebration at the Shanghai Club,annotations_enc_rotary_en_1319843498.json,1319843498_11,Armistice celebration at the Shanghai Club,1.000000
11,1319843498_12,Guests assembled in the banquet hall for supper,annotations_enc_rotary_en_1319843498.json,1319854677_2,Bitter opposition has been raised among all cl...,0.415130
12,1319843498_13,Vocal solos rendered in the ballroom during th...,annotations_enc_rotary_en_1319843498.json,1319843498_3,social evening hearts drive and dance will be ...,0.428769
13,1319843498_14,American Woman's Club decides to hold an infor...,annotations_enc_rotary_en_1319843498.json,1319843498_13,dinner given by YangTcheng Commissioner of For...,0.507683
14,1319843498_15,"Dinner given by YangTcheng, Commissioner of Fo...",annotations_enc_rotary_en_1319843498.json,1319843498_13,dinner given by YangTcheng Commissioner of For...,0.960338
15,1319854677_01,Proclamations issued enjoining slaughter of pi...,annotations_enc_rotary_en_1319854677.json,1319854677_1,Proclamations were issued enjoining the slaugh...,0.881545
16,1319854677_03,Peking officials prayed for rain; people ate s...,annotations_enc_rotary_en_1319854677.json,1319854677_2,Bitter opposition has been raised among all cl...,0.511489
17,1319854677_04,Bitter opposition raised against the newly pro...,annotations_enc_rotary_en_1319854677.json,1319854677_2,Bitter opposition has been raised among all cl...,0.845747
18,1319854677_05,About 180 Peiyang students quartered themselve...,annotations_enc_rotary_en_1319854677.json,1319854677_5,By presidential mandates issued Yueh Chao-chu ...,0.472399
19,1319854677_06,"Liang Tun-yen, former minister of communicatio...",annotations_enc_rotary_en_1319854677.json,po_en_1669_1,President Chen Shui-bian presided over a cerem...,0.525199
20,1319854677_07,General Li Yuan-hung returned to his Tientsin ...,annotations_enc_rotary_en_1319854677.json,1319854677_4,General Li Yuan-hung returned to his Tientsin ...,0.961006
21,1319854677_08,Presidential mandates appointed Yueh Chao-chu ...,annotations_enc_rotary_en_1319854677.json,1319854677_5,By presidential mandates issued Yueh Chao-chu ...,0.928508
22,1319854677_09,Two main lines of the Peking tramways to begin...,annotations_enc_rotary_en_1319854677.json,1319854677_6,two of the main lines of the Peking tramways w...,0.870419
23,1319854677_10,Fliers practising day and night in and around ...,annotations_enc_rotary_en_1319854677.json,1319854677_4,General Li Yuan-hung returned to his Tientsin ...,0.417538
24,1319854677_11,About 200 Chinese held a meeting in Central Pa...,annotations_enc_rotary_en_1319854677.json,1319854677_7,held meeting in the Central Park of Peking,0.624589
25,1319854677_12,"Burgess, secretary of the Community Service de...",annotations_enc_rotary_en_1319854677.json,po_en_1669_1,President Chen Shui-bian presided over a cerem...,0.545117
26,1319854677_13,"Dr Jacob Gould Schurman, American Minister to ...",annotations_enc_rotary_en_1319854677.json,1319854677_9,Dr Jacob Gould Schurman left Peking for Tientsin,0.745983
27,1319854677_14,They left for Taian for a sightseeing trip up ...,annotations_enc_rotary_en_1319854677.json,1319843498_9,They departed on their wedding trip to Chungking,0.459275
28,1319854677_15,Mrs Schurman to return to Peking; Dr Schurman ...,annotations_enc_rotary_en_1319854677.json,1319843498_10,returning in December to Shanghai,0.529605
29,1319854677_16,"General William Conner, aides, and Mr Peck lef...",annotations_enc_rotary_en_1319854677.json,1319854677_10,General William Conner left Peking for Loyang,0.768494
30,1319854677_17,"Hiram Cleaver, ex-president of the Continental...",annotations_enc_rotary_en_1319854677.json,1319854677_11,Hiram Cleaver and Mrs Cleaver arrived in Peking,0.738234
31,1319854677_18,An unidentified messenger brought a package to...,annotations_enc_rotary_en_1319854677.json,po_en_1669_1,President Chen Shui-bian presided over a cerem...,0.473980
32,1319854677_19,"Dr Koo ordered a package opened, resulting in ...",annotations_enc_rotary_en_1319854677.json,1319854677_2,Bitter opposition has been raised among all cl...,0.452274
33,INSCR-KR4d0232-WYG-f006-0002_01,始作浮梁,INSCR-KR4d0232-WYG-f006-0002.json,KR4d0232-WYG-f006-0002_1,陳侯森始作浮梁,0.671316
34,INSCR-KR4d0232-WYG-f006-0002_02,漂航斷笮／橋毁,INSCR-KR4d0232-WYG-f006-0002.json,KR4d0232-WYG-f006-0002_2,甚雨淫潦漂航斷笮,0.426202
35,INSCR-KR4d0232-WYG-f006-0002_03,造端,INSCR-KR4d0232-WYG-f006-0002.json,KR4d0232-WYG-f006-0002_3,趙景明復新之橋造端,0.339715
36,INSCR-KR4d0232-WYG-f006-0002_04,告具,INSCR-KR4d0232-WYG-f006-0002.json,KR4d0232-WYG-f006-0002_4,橋告具,0.707856
37,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_1,橋燬,0.133478
38,INSCR-KR4d0466-WYG-f011-0010_02,度材鳩工,INSCR-KR4d0466-WYG-f011-0010.json,po_zh_8342_1,陳總統水扁先生前往南投縣埔里鎮參加國道六號南投段開工動土典禮,0.024285
39,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_3,橋始事,0.686363
40,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_4,橋落成,0.707856
41,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_3,橋始事,0.410221
42,SPSP192506121501_01,天津扶輪社電上海扶輪社日前接天津扶輪社來電略謂天津扶輪社同人敬以同氣之誼致候上海扶輪社諸君並...,annotations_enc_rotary_cmn_SPSP192506121501.json,SPSP192506121501_1,天津扶輪社電上海扶輪社,0.760379
43,SPSP192506121501_02,該社當即擬覆略謂敬問起居卓見深合私衷同人等正盡力重建相尊相信之原則,annotations_enc_rotary_cmn_SPSP192506121501.json,SPSP192506121501_1,天津扶輪社電上海扶輪社,0.022903
44,SPSP193109022001_01,扶輪社明日聚餐會上海扶輪社本星期四午間十二時三十分、在老卡爾登舉行聚餐會,annotations_enc_rotary_cmn_SPSP193109022001.json,SPSP193109022001_1,上海扶輪社舉行聚餐會,0.554862
45,SPSP193109022001_02,請安德魯博士演講最近探險蒙古沙漠情形,annotations_enc_rotary_cmn_SPSP193109022001.json,SPSP192708311019_2,黃倩儀受碩士銜,0.026275
46,TW_001,Feb. 25 (CNA) President Chen Shui-bian preside...,po_en_1669.json,po_en_1669_1,President Chen Shui-bian presided over a cerem...,0.844928
47,TW_002,Meeting the delegation at the Presidential Bui...,po_en_1.json,po_en_1_1,Vice President Vincent C. Siew met with the In...,0.678340
48,TW_003,"Over the years, the conference has served as a...",po_en_1.json,1319843498_3,social evening hearts drive and dance will be ...,0.588498
49,po_zh_2376_00,有關今（二十七）日「中時晚報」及「勁報」報導「總統府公務車撞六車傷五人」乙事，因與事實不符，...,structure_example_TW_po_zh_2376.json,po_zh_2376_1,中時晚報及勁報報導總統府公務車撞六車傷五人,0.506014
50,po_zh_2376_01,今天上午在台北市羅斯福路所發生疑似暴衝之連環車禍,structure_example_TW_po_zh_2376.json,po_zh_2376_2,台北市羅斯福路發生疑似暴衝之連環車禍,0.792059
51,po_zh_8342_00,陳總統水扁先生今天下午前往南投縣埔里鎮參加國道六號南投段開工動土典禮，並應邀致詞。,structure_example_TW_po_zh_8342_ZC.json,po_zh_8342_1,陳總統水扁先生前往南投縣埔里鎮參加國道六號南投段開工動土典禮,0.805039
52,po_zh_8342_01,今天阿扁非常高興到南投埔里，來參加「新十大建設」在中部地區最重大工程之一：「國道六號南投段」...,structure_example_TW_po_zh_8342_ZC.json,po_zh_8342_1,陳總統水扁先生前往南投縣埔里鎮參加國道六號南投段開工動土典禮,0.283455
53,po_zh_8342_02,當年政府開發中部橫貫公路,structure_example_TW_po_zh_8342_ZC.json,po_zh_8342_2,第二高速公路全線通車,0.070819
54,po_zh_8342_03,隨著「第二高速公路」於今年1月全線通車,structure_example_TW_po_zh_8342_ZC.json,po_zh_8342_2,第二高速公路全線通車,0.581264
55,po_zh_8342_04,十二條「東西向快速道路」、「西濱快速公路」，以及「高速鐵路」於明年十月開始營運通車,structure_example_TW_po_zh_8342_ZC.json,po_zh_8342_3,高速鐵路開始營運通車,0.387670
56,po_zh_8342_05,過去半年以來，股市與房市不斷加溫,structure_example_TW_po_zh_8342_ZC.json,po_zh_2376_2,台北市羅斯福路發生疑似暴衝之連環車禍,0.034662
57,po_zh_8342_06,在開工今天，祝福我們國道工程一切順利,structure_example_TW_po_zh_8342_ZC.json,po_zh_8342_1,陳總統水扁先生前往南投縣埔里鎮參加國道六號南投段開工動土典禮,0.071347

======================================================================
完成
======================================================================

Source Events：
/content/source_events_with_event_id.csv

Schema Events：
/content/schema_events_with_event_id.csv

Complete Pairwise Similarity：
/content/source_vs_schema_event_cosine_similarity.csv

Best Match：
/content/source_vs_schema_best_event_match.csv