In [14]:
import os
import json
import re
import pandas as pd

In [3]:
OUTPUT_PATH = "./outputs/"
ANNOTATIONS_PATH = "./annotations_remarks/annotations"
EXTRACTIONS_PATH = "./outputs"

In [222]:
annotations = []
for filename in os.listdir(ANNOTATIONS_PATH):
    filepath = os.path.join(ANNOTATIONS_PATH, filename)
    if os.path.isfile(filepath):
        with open(filepath, "r", encoding="utf-8") as f:
            print(filepath)
            annotation_raw =f.read()
            annot = json.loads(annotation_raw)
            annot = annot[list(annot.keys())[0]]
            annotations.extend(annot["events"])

./annotations_remarks/annotations/po_en_1669.json
./annotations_remarks/annotations/annotations_enc_rotary_en_1319854677.json
./annotations_remarks/annotations/INSCR-KR4d0232-WYG-f006-0002.json
./annotations_remarks/annotations/annotations_enc_rotary_cmn_SPSP193109022001.json
./annotations_remarks/annotations/structure_example_TW_po_zh_8342_ZC.json
./annotations_remarks/annotations/structure_example_TW_po_zh_2376.json
./annotations_remarks/annotations/annotations_enc_rotary_en_1319843498.json
./annotations_remarks/annotations/annotations_enc_exp_cmn_SPSP192606271118.json
./annotations_remarks/annotations/annotations_enc_exp_cmn_SPSP192708311019.json
./annotations_remarks/annotations/po_en_1.json
./annotations_remarks/annotations/annotations_enc_rotary_cmn_SPSP192506121501.json
./annotations_remarks/annotations/INSCR-KR4d0466-WYG-f011-0010.json

In [225]:
len(annotations)

75

In [11]:
extractions =[]
with open(os.path.join(EXTRACTIONS_PATH,"extraction_events_final_schema.json" )) as infile:
    extractions = json.load(infile)
extract_events = extractions["events"]

In [226]:
wrapped = [
    x if isinstance(x, dict) else {"nested": x}
    for x in annotations
]
df_source = pd.json_normalize(wrapped)
df_source

,event_id,event_name,event_sources,time_start,time_end,range,event_time_start,event_time_end
0,TW_001,Feb. 25 (CNA) President Chen Shui-bian preside...,"[{'filename': './TW/po/eng/po_en_1669.txt', 't...",XXXX-02-25,Null,Null,NaN,NaN
1,1319854677_01,Proclamations issued enjoining slaughter of pi...,"[{'filename': '1319854677.txt', 'time_related_...","[this week, this week]",None,None,NaN,NaN
2,1319854677_03,Peking officials prayed for rain; people ate s...,"[{'filename': '1319854677.txt', 'time_related_...","[None, None]",None,"[(3, days)]",NaN,NaN
3,1319854677_04,Bitter opposition raised against the newly pro...,"[{'filename': '1319854677.txt', 'time_related_...","[this week, this week]",None,None,NaN,NaN
4,1319854677_05,About 180 Peiyang students quartered themselve...,"[{'filename': '1319854677.txt', 'time_related_...","[None, None]",None,"[(1, week), (1, week))]",NaN,NaN
...,...,...,...,...,...,...,...,...
70,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[至元丙子, 至元丙子]","[至元丙子, 至元丙子]",None,NaN,NaN
71,INSCR-KR4d0466-WYG-f011-0010_02,度材鳩工,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[壬辰六月, 壬辰六月]","[壬辰六月, 壬辰六月]",None,NaN,NaN
72,INSCR-KR4d0466-WYG-f011-0010_03,始事,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[癸已十一月, 癸已十一月]","[癸已十一月, 癸已十一月]",None,NaN,NaN
73,INSCR-KR4d0466-WYG-f011-0010_04,落成,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[越明年七月, 越明年七月]","[越明年七月, 越明年七月]",None,NaN,NaN
74,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[甲午, 甲午]","[甲午, 甲午]",None,NaN,NaN

In [227]:
df_source.rename({"event_id":"source_event_id"})
df_source

,event_id,event_name,event_sources,time_start,time_end,range,event_time_start,event_time_end
0,TW_001,Feb. 25 (CNA) President Chen Shui-bian preside...,"[{'filename': './TW/po/eng/po_en_1669.txt', 't...",XXXX-02-25,Null,Null,NaN,NaN
1,1319854677_01,Proclamations issued enjoining slaughter of pi...,"[{'filename': '1319854677.txt', 'time_related_...","[this week, this week]",None,None,NaN,NaN
2,1319854677_03,Peking officials prayed for rain; people ate s...,"[{'filename': '1319854677.txt', 'time_related_...","[None, None]",None,"[(3, days)]",NaN,NaN
3,1319854677_04,Bitter opposition raised against the newly pro...,"[{'filename': '1319854677.txt', 'time_related_...","[this week, this week]",None,None,NaN,NaN
4,1319854677_05,About 180 Peiyang students quartered themselve...,"[{'filename': '1319854677.txt', 'time_related_...","[None, None]",None,"[(1, week), (1, week))]",NaN,NaN
...,...,...,...,...,...,...,...,...
70,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[至元丙子, 至元丙子]","[至元丙子, 至元丙子]",None,NaN,NaN
71,INSCR-KR4d0466-WYG-f011-0010_02,度材鳩工,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[壬辰六月, 壬辰六月]","[壬辰六月, 壬辰六月]",None,NaN,NaN
72,INSCR-KR4d0466-WYG-f011-0010_03,始事,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[癸已十一月, 癸已十一月]","[癸已十一月, 癸已十一月]",None,NaN,NaN
73,INSCR-KR4d0466-WYG-f011-0010_04,落成,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[越明年七月, 越明年七月]","[越明年七月, 越明年七月]",None,NaN,NaN
74,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[甲午, 甲午]","[甲午, 甲午]",None,NaN,NaN

In [228]:
df_schema = pd.json_normalize(extract_events)

In [229]:
df_schema

,event_id,event_name,event_sources,time_start,time_end,range
0,po_zh_2376_1,中時晚報及勁報報導總統府公務車撞六車傷五人,"[{'filename': 'po_zh_2376.txt', 'time_related_...","('27日', '27日')","('27日', '27日')","((day,27),(day,27))"
1,po_zh_2376_2,台北市羅斯福路發生疑似暴衝之連環車禍,"[{'filename': 'po_zh_2376.txt', 'time_related_...","(今天上午, 今天上午)","(今天上午, 今天上午)","((half_day,上午),(half_day,上午))"
2,po_en_1669_1,President Chen Shui-bian presided over a cerem...,"[{'filename': 'po_en_1669.txt', 'time_related_...","(Feb. 25 Wednesday, Feb. 25 Wednesday)","(Feb. 25 Wednesday, Feb. 25 Wednesday)",NaN
3,SPSP192606271118_1,沈鴻來入美國俄伯靈大學經濟銀行科,"[{'filename': 'SPSP192606271118.txt', 'time_re...","('民國十三年八月', '民國十三年八月')","('民國十三年八月', '民國十三年八月')","((month,8),(month,8))"
4,SPSP192606271118_2,沈鴻來以第一名畢業獲學士位,"[{'filename': 'SPSP192606271118.txt', 'time_re...","('十五年二月', '十五年二月')","('十五年二月', '十五年二月')","((month,2),(month,2))"
5,KR4d0466-WYG-f011-0010_1,橋燬,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('至元丙子', '至元丙子')","('至元丙子', '至元丙子')",NaN
6,KR4d0466-WYG-f011-0010_2,為梁以濟,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('壬辰六月', '壬辰六月')","('壬辰六月', '壬辰六月')","((month,6),(month,6))"
7,KR4d0466-WYG-f011-0010_3,橋始事,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('癸已十一月', '癸已十一月')","('癸已十一月', '癸已十一月')","((month,11),(month,11))"
8,KR4d0466-WYG-f011-0010_4,橋落成,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('越明年七月', '越明年七月')","('越明年七月', '越明年七月')","((month,7),(month,7))"
9,SPSP192506121501_1,天津扶輪社電上海扶輪社,"[{'filename': 'SPSP192506121501.txt', 'time_re...","('日前', '日前')","('日前', '日前')",NaN
10,po_en_1_1,Vice President Vincent C. Siew met with the In...,"[{'filename': 'po_en_1.txt', 'time_related_exp...","(July 30 morning, July 30 morning)","(July 30 morning, July 30 morning)","((half_day,morning),(half_day,morning))"
11,KR4d0232-WYG-f006-0002_1,陳侯森始作浮梁,"[{'filename': 'KR4d0232-WYG-f006-0002.txt', 't...","('乾道初元', '乾道初元')","('乾道初元', '乾道初元')",NaN
12,KR4d0232-WYG-f006-0002_2,甚雨淫潦漂航斷笮,"[{'filename': 'KR4d0232-WYG-f006-0002.txt', 't...","('淳熈二年秋七月', '淳熈二年秋七月')","('淳熈二年秋七月', '淳熈二年秋七月')","((month,7),(month,7))"
13,KR4d0232-WYG-f006-0002_3,趙景明復新之橋造端,"[{'filename': 'KR4d0232-WYG-f006-0002.txt', 't...","('十月戊寅', '十月戊寅')","('十月戊寅', '十月戊寅')","((month,10),(month,10))"
14,KR4d0232-WYG-f006-0002_4,橋告具,"[{'filename': 'KR4d0232-WYG-f006-0002.txt', 't...","('十一月丁丑', '十一月丁丑')","('十一月丁丑', '十一月丁丑')","((month,11),(month,11))"
15,1319854677_1,Proclamations were issued enjoining the slaugh...,"[{'filename': '1319854677.txt', 'time_related_...","(this week, this week)","(this week, this week)","((week,1),(week,1))"
16,1319854677_2,Bitter opposition has been raised among all cl...,"[{'filename': '1319854677.txt', 'time_related_...","(this week, this week)","(this week, this week)","((week,1),(week,1))"
17,1319854677_3,Liang Tun-yen passed away,"[{'filename': '1319854677.txt', 'time_related_...","('May 12', 'May 12')","('May 12', 'May 12')",NaN
18,1319854677_4,General Li Yuan-hung returned to his Tientsin ...,"[{'filename': '1319854677.txt', 'time_related_...","('May 10', 'May 10')","('May 10', 'May 10')",NaN
19,1319854677_5,By presidential mandates issued Yueh Chao-chu ...,"[{'filename': '1319854677.txt', 'time_related_...","(Monday night, Monday night)","(Monday night, Monday night)",NaN
20,1319854677_6,two of the main lines of the Peking tramways w...,"[{'filename': '1319854677.txt', 'time_related_...","('July 1', 'July 1')","('July 1', 'July 1')",NaN
21,1319854677_7,held meeting in the Central Park of Peking,"[{'filename': '1319854677.txt', 'time_related_...","('May 15', 'May 15')","('May 15', 'May 15')",NaN
22,1319854677_8,Burgess left for Shanghai,"[{'filename': '1319854677.txt', 'time_related_...","('May 15', 'May 15')","('May 15', 'May 15')",NaN
23,1319854677_9,Dr Jacob Gould Schurman left Peking for Tientsin,"[{'filename': '1319854677.txt', 'time_related_...","('May 14', 'May 14')","('May 14', 'May 14')",NaN
24,1319854677_10,General William Conner left Peking for Loyang,"[{'filename': '1319854677.txt', 'time_related_...","('May 12', 'May 12')","('May 12', 'May 12')",NaN
25,1319854677_11,Hiram Cleaver and Mrs Cleaver arrived in Peking,"[{'filename': '1319854677.txt', 'time_related_...","('May 14', 'May 14')","('May 14', 'May 14')",NaN
26,1319843498_1,120 women enrolled for ten days course of lect...,"[{'filename': '1319843498.txt', 'time_related_...","(last week, last week)","(last week, last week)","((week,1),(week,1))"
27,1319843498_2,Jean Alvalyn was born to Mr and Mrs Cannon at ...,"[{'filename': '1319843498.txt', 'time_related_...","('November 6', 'November 6')","('November 6', 'November 6')",NaN
28,1319843498_3,social evening hearts drive and dance will be ...,"[{'filename': '1319843498.txt', 'time_related_...","('Friday November 14', 'Friday November 14')","('Friday November 14', 'Friday November 14')",NaN
29,1319843498_4,Mrs George Fryer will be at home to her freinds,"[{'filename': '1319843498.txt', 'time_related_...","('November 14', 'November 14')","('November 21', 'November 21')",NaN
30,1319843498_5,announcement is made of the marriage of Dr Amy...,"[{'filename': '1319843498.txt', 'time_related_...","('October 29', 'October 29')","('October 29', 'October 29')",NaN
31,1319843498_6,Mrs Bowen left China for France,"[{'filename': '1319843498.txt', 'time_related_...","('June', 'June')","('June', 'June')","((month,6),(month,6))"
32,1319843498_7,reception was given to parents and their frien...,"[{'filename': '1319843498.txt', 'time_related_...","('November 11', 'November 11')","('November 11', 'November 11')","((half_day,afternoon),(half_day,afternoon))"
33,1319843498_8,wedding took place at Hankow China of John Bri...,"[{'filename': '1319843498.txt', 'time_related_...","('November 2', 'November 2')","('November 2', 'November 2')",NaN
34,1319843498_9,They departed on their wedding trip to Chungking,"[{'filename': '1319843498.txt', 'time_related_...",NaN,NaN,NaN
35,1319843498_10,returning in December to Shanghai,"[{'filename': '1319843498.txt', 'time_related_...","('December', 'December')","('December', 'December')","((month,12),(month,12))"
36,1319843498_11,Armistice celebration at the Shanghai Club,"[{'filename': '1319843498.txt', 'time_related_...","('November 11', 'November 11')","('November 11', 'November 11')","((half_day,evening),(half_day,evening))"
37,1319843498_12,at home held on Saturday evening November 8,"[{'filename': '1319843498.txt', 'time_related_...","('November 8', 'November 8')","('November 8', 'November 8')","((half_day,evening),(half_day,evening))"
38,1319843498_13,dinner given by YangTcheng Commissioner of For...,"[{'filename': '1319843498.txt', 'time_related_...","('November 8', 'November 8')","('November 8', 'November 8')","((half_day,evening),(half_day,evening))"
39,po_zh_8342_1,陳總統水扁先生前往南投縣埔里鎮參加國道六號南投段開工動土典禮,"[{'filename': 'po_zh_8342.txt', 'time_related_...","(今天下午, 今天下午)","(今天下午, 今天下午)","((half_day,下午),(half_day,下午))"
40,po_zh_8342_2,第二高速公路全線通車,"[{'filename': 'po_zh_8342.txt', 'time_related_...","('今年1月', '今年1月')","('今年1月', '今年1月')","((month,1),(month,1))"
41,po_zh_8342_3,高速鐵路開始營運通車,"[{'filename': 'po_zh_8342.txt', 'time_related_...","('明年十月', '明年十月')","('明年十月', '明年十月')","((month,10),(month,10))"
42,SPSP192708311019_1,黃倩儀考入清華官費出洋,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('一九二一年', '一九二一年')","('一九二一年', '一九二一年')",NaN
43,SPSP192708311019_2,黃倩儀受碩士銜,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('一九二五年', '一九二五年')","('一九二五年', '一九二五年')",NaN
44,SPSP192708311019_3,黃倩儀取道歐洲回國,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('今夏七月間', '今夏七月間')","('今夏七月間', '今夏七月間')","((month,7),(month,7))"
45,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('一九二一年', '一九二一年')","('一九二一年', '一九二一年')",NaN
46,SPSP192708311019_5,黃倩鴻回國,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('一九二六年春季', '一九二六年春季')","('一九二六年春季', '一九二六年春季')","((season,春季),(season,春季))"
47,SPSP193109022001_1,上海扶輪社舉行聚餐會,"[{'filename': 'SPSP193109022001.txt', 'time_re...","('本星期四午間十二時三十分', '本星期四午間十二時三十分')","('本星期四午間十二時三十分', '本星期四午間十二時三十分')","((hour,午間十二時三十分),(hour,午間十二時三十分))"

So now, we have:
- the annotated events, with their set of ids $a_i$ and their event names $a^l_i$ 
- the extracted events with their set of ids $p_i$ and their event names $p^l_i$.

We need to match $p^l_i$ and $a^l_i$ to be able to then match $p_i$ to $a_i$. 

This will enable us to check if the LLM:
- extracted the right events
- grouped events that annotators thought were 2 different events
- split events differently than annotators

# Source and schema matching

In [230]:
df_matched = pd.read_csv("/home/ADWKS.UHB.FR/mallart_c/Documents/hackaton_llm_temporal_reasoning/distimellm/LLMs/outputs/semantic_matching_event_names/source_vs_schema_best_event_match.csv")

Matching df_annots and df_extract using df_matched

In [231]:
matches = df_matched[["source_event_id", "schema_event_id"]]
matches

                    source_event_id           schema_event_id
0                     1319843498_01              1319843498_1
1                     1319843498_02              1319843498_2
2                     1319843498_03              1319843498_3
3                     1319843498_04              1319843498_4
4                     1319843498_05              1319843498_4
5                     1319843498_06              1319843498_5
6                     1319843498_07              1319843498_6
7                     1319843498_08              1319843498_7
8                     1319843498_09              1319843498_8
9                     1319843498_10              1319843498_9
10                    1319843498_11             1319843498_11
11                    1319843498_12              1319854677_2
12                    1319843498_13              1319843498_3
13                    1319843498_14             1319843498_13
14                    1319843498_15             1319843498_13
15                    1319854677_01              1319854677_1
16                    1319854677_03              1319854677_2
17                    1319854677_04              1319854677_2
18                    1319854677_05              1319854677_5
19                    1319854677_06              po_en_1669_1
20                    1319854677_07              1319854677_4
21                    1319854677_08              1319854677_5
22                    1319854677_09              1319854677_6
23                    1319854677_10              1319854677_4
24                    1319854677_11              1319854677_7
25                    1319854677_12              po_en_1669_1
26                    1319854677_13              1319854677_9
27                    1319854677_14              1319843498_9
28                    1319854677_15             1319843498_10
29                    1319854677_16             1319854677_10
30                    1319854677_17             1319854677_11
31                    1319854677_18              po_en_1669_1
32                    1319854677_19              1319854677_2
33  INSCR-KR4d0232-WYG-f006-0002_01  KR4d0232-WYG-f006-0002_1
34  INSCR-KR4d0232-WYG-f006-0002_02  KR4d0232-WYG-f006-0002_2
35  INSCR-KR4d0232-WYG-f006-0002_03  KR4d0232-WYG-f006-0002_3
36  INSCR-KR4d0232-WYG-f006-0002_04  KR4d0232-WYG-f006-0002_4
37  INSCR-KR4d0466-WYG-f011-0010_01  KR4d0466-WYG-f011-0010_1
38  INSCR-KR4d0466-WYG-f011-0010_02              po_zh_8342_1
39  INSCR-KR4d0466-WYG-f011-0010_03  KR4d0466-WYG-f011-0010_3
40  INSCR-KR4d0466-WYG-f011-0010_04  KR4d0466-WYG-f011-0010_4
41  INSCR-KR4d0466-WYG-f011-0010_05  KR4d0466-WYG-f011-0010_3
42              SPSP192506121501_01        SPSP192506121501_1
43              SPSP192506121501_02        SPSP192506121501_1
44              SPSP193109022001_01        SPSP193109022001_1
45              SPSP193109022001_02        SPSP192708311019_2
46                           TW_001              po_en_1669_1
47                           TW_002                 po_en_1_1
48                           TW_003              1319843498_3
49                    po_zh_2376_00              po_zh_2376_1
50                    po_zh_2376_01              po_zh_2376_2
51                    po_zh_8342_00              po_zh_8342_1
52                    po_zh_8342_01              po_zh_8342_1
53                    po_zh_8342_02              po_zh_8342_2
54                    po_zh_8342_03              po_zh_8342_2
55                    po_zh_8342_04              po_zh_8342_3
56                    po_zh_8342_05              po_zh_2376_2
57                    po_zh_8342_06              po_zh_8342_1

In [232]:
print(len(matches.source_event_id.unique()))
print(len(matches.schema_event_id.unique()))
print(len(matches.drop_duplicates()))

58
38
58

 Conclusion : there are many different source events matched for a single schema event.

 So we need to go back to similarity to find the best matching source events for a given schema event

bipartite matching problem => greedy algo

In [233]:
df_similarity =pd.read_csv("./outputs/semantic_matching_event_names/source_vs_schema_event_cosine_similarity.csv")

In [234]:
len(df_similarity)

2832

We remove when there is similarity of 0 + 
we need to remove when the filenames are not the same (bc then they're obviously not the same event) => hard to do for now

In [235]:
df_sim = df_similarity[df_similarity.cosine_similarity != 0]
#df_sim = df_sim[df_sim['source_event_id'].str[:10] == df_sim['schema_event_id'].str[:10]]

In [236]:
len(df_sim)

1086

In [237]:
print(len(df_sim.source_event_id.unique()))
print(len(df_sim.schema_event_id.unique()))
print(len(df_sim.drop_duplicates()))

58
48
1086

In [238]:
import pandas as pd
from scipy.sparse import coo_matrix
from scipy.sparse.csgraph import min_weight_full_bipartite_matching
import numpy as np

In [239]:
df_sorted = df_sim.sort_values('cosine_similarity', ascending=False)

used_schema, used_source = set(), set()
rows = []

for r in df_sorted.itertuples(index=False):
    if r.schema_event_id not in used_schema and r.source_event_id not in used_source:
        rows.append(r)
        used_schema.add(r.schema_event_id)
        used_source.add(r.source_event_id)

df_matched = pd.DataFrame(rows, columns=df_sim.columns)

In [240]:
print(len(df_matched))
print(len(df_matched.source_event_id.unique()))
print(len(df_matched.schema_event_id.unique()))

#every id is unique then !

45
45
45

In [241]:
# Step 1: df_source -> matches (outer keeps df_source events with no match)
merged = pd.merge(
    df_source,
    df_matched,
    left_on='event_id',
    right_on='source_event_id',
    how='outer'
)

In [243]:
merged

,event_id,event_name,event_sources,time_start,time_end,range,event_time_start,event_time_end,source_event_id,source_event_name,source_file,schema_event_id,schema_event_name,cosine_similarity
0,1319843498_01,120 women enrolled in a ten-day course of lect...,"[{'filename': '1319843498.txt', 'time_related_...","[last week, last week]",None,"[[days, 10], [days, 10]]",NaN,NaN,1319843498_01,120 women enrolled in a ten-day course of lect...,annotations_enc_rotary_en_1319843498.json,1319843498_1,120 women enrolled for ten days course of lect...,0.808312
1,1319843498_02,Jean Alvalyn born to Mr and Mrs Cannon at Fooc...,"[{'filename': '1319843498.txt', 'time_related_...","[XXXX-11-06, XXXX-11-06]",None,None,NaN,NaN,1319843498_02,Jean Alvalyn born to Mr and Mrs Cannon at Fooc...,annotations_enc_rotary_en_1319843498.json,1319843498_2,Jean Alvalyn was born to Mr and Mrs Cannon at ...,0.921457
2,1319843498_03,"Social evening, hearts drive and dance at the ...","[{'filename': '1319843498.txt', 'time_related_...","[XXXX-11-14, XXXX-11-14]",None,"[[evening, 1], [evening, 1]]",NaN,NaN,1319843498_03,"Social evening, hearts drive and dance at the ...",annotations_enc_rotary_en_1319843498.json,1319843498_3,social evening hearts drive and dance will be ...,0.905611
3,1319843498_04,Mrs George Fryer at home to friends at No 4 Ed...,"[{'filename': '1319843498.txt', 'time_related_...","[XXXX-11-14T16:XX, XXXX-11-14T16:XX]","[XXXX-11-14T18:XX, XXXX-11-14T18:XX]",None,NaN,NaN,1319843498_04,Mrs George Fryer at home to friends at No 4 Ed...,annotations_enc_rotary_en_1319843498.json,1319843498_4,Mrs George Fryer will be at home to her freinds,0.659179
4,1319843498_05,Mrs George Fryer at home to friends at No 4 Ed...,"[{'filename': '1319843498.txt', 'time_related_...","[XXXX-11-21T16:XX, XXXX-11-21T16:XX]","[XXXX-11-21T18:XX, XXXX-11-21T18:XX]",None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,po_zh_8342_02,當年政府開發中部橫貫公路,"[{'filename': 'po_zh_8342.txt', 'time_related_...",Null,Null,Null,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,po_zh_8342_03,隨著「第二高速公路」於今年1月全線通車,"[{'filename': 'po_zh_8342.txt', 'time_related_...",2004-01-01,2004-01-31,"(month, 1)",NaN,NaN,po_zh_8342_03,隨著「第二高速公路」於今年1月全線通車,structure_example_TW_po_zh_8342_ZC.json,po_zh_8342_2,第二高速公路全線通車,0.581264
72,po_zh_8342_04,十二條「東西向快速道路」、「西濱快速公路」，以及「高速鐵路」於明年十月開始營運通車,"[{'filename': 'po_zh_8342.txt', 'time_related_...",Null,Null,Null,NaN,NaN,po_zh_8342_04,十二條「東西向快速道路」、「西濱快速公路」，以及「高速鐵路」於明年十月開始營運通車,structure_example_TW_po_zh_8342_ZC.json,po_zh_8342_3,高速鐵路開始營運通車,0.387670
73,po_zh_8342_05,過去半年以來，股市與房市不斷加溫,"[{'filename': 'po_zh_8342.txt', 'time_related_...",2003-08-25,2004-02-25,"(month, 6)",NaN,NaN,po_zh_8342_05,過去半年以來，股市與房市不斷加溫,structure_example_TW_po_zh_8342_ZC.json,KR4d0466-WYG-f011-0010_2,為梁以濟,0.032207
74,po_zh_8342_06,在開工今天，祝福我們國道工程一切順利,"[{'filename': 'po_zh_8342.txt', 'time_related_...",2004-02-25,2004-02-25,Null,NaN,NaN,po_zh_8342_06,在開工今天，祝福我們國道工程一切順利,structure_example_TW_po_zh_8342_ZC.json,SPSP192708311019_3,黃倩儀取道歐洲回國,0.034779

In [193]:
# Step 2: step1 -> df_schema (outer keeps df_schema events with no match)
result = step1.merge(
    df_schema,
    left_on="schema_event_id",
    right_on="event_id",
    how="inner",
    suffixes=("_source", "_schema")
)
print(len(result))
print(len(df_schema))

48
48

In [194]:
result

,event_id_source,event_name_source,event_sources_source,time_start_source,time_end_source,range_source,source_event_id,source_event_name,source_file,schema_event_id,schema_event_name,cosine_similarity,event_id_schema,event_name_schema,event_sources_schema,time_start_schema,time_end_schema,range_schema
0,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[至元丙子, 至元丙子]","[至元丙子, 至元丙子]",None,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,INSCR-KR4d0466-WYG-f011-0010.json,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,0.020504,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('一九二一年', '一九二一年')","('一九二一年', '一九二一年')",NaN
1,INSCR-KR4d0466-WYG-f011-0010_03,始事,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[癸已十一月, 癸已十一月]","[癸已十一月, 癸已十一月]",None,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_3,橋始事,0.686363,KR4d0466-WYG-f011-0010_3,橋始事,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('癸已十一月', '癸已十一月')","('癸已十一月', '癸已十一月')","((month,11),(month,11))"
2,INSCR-KR4d0466-WYG-f011-0010_04,落成,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[越明年七月, 越明年七月]","[越明年七月, 越明年七月]",None,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_4,橋落成,0.707856,KR4d0466-WYG-f011-0010_4,橋落成,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('越明年七月', '越明年七月')","('越明年七月', '越明年七月')","((month,7),(month,7))"
3,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[甲午, 甲午]","[甲午, 甲午]",None,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_1,橋燬,0.155878,KR4d0466-WYG-f011-0010_1,橋燬,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('至元丙子', '至元丙子')","('至元丙子', '至元丙子')",NaN
4,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[至元丙子, 至元丙子]","[至元丙子, 至元丙子]",None,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,INSCR-KR4d0466-WYG-f011-0010.json,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,0.020504,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('一九二一年', '一九二一年')","('一九二一年', '一九二一年')",NaN
5,INSCR-KR4d0466-WYG-f011-0010_03,始事,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[癸已十一月, 癸已十一月]","[癸已十一月, 癸已十一月]",None,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_3,橋始事,0.686363,KR4d0466-WYG-f011-0010_3,橋始事,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('癸已十一月', '癸已十一月')","('癸已十一月', '癸已十一月')","((month,11),(month,11))"
6,INSCR-KR4d0466-WYG-f011-0010_04,落成,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[越明年七月, 越明年七月]","[越明年七月, 越明年七月]",None,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_4,橋落成,0.707856,KR4d0466-WYG-f011-0010_4,橋落成,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('越明年七月', '越明年七月')","('越明年七月', '越明年七月')","((month,7),(month,7))"
7,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[甲午, 甲午]","[甲午, 甲午]",None,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_1,橋燬,0.155878,KR4d0466-WYG-f011-0010_1,橋燬,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('至元丙子', '至元丙子')","('至元丙子', '至元丙子')",NaN
8,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[至元丙子, 至元丙子]","[至元丙子, 至元丙子]",None,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,INSCR-KR4d0466-WYG-f011-0010.json,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,0.020504,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('一九二一年', '一九二一年')","('一九二一年', '一九二一年')",NaN
9,INSCR-KR4d0466-WYG-f011-0010_03,始事,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[癸已十一月, 癸已十一月]","[癸已十一月, 癸已十一月]",None,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_3,橋始事,0.686363,KR4d0466-WYG-f011-0010_3,橋始事,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('癸已十一月', '癸已十一月')","('癸已十一月', '癸已十一月')","((month,11),(month,11))"
10,INSCR-KR4d0466-WYG-f011-0010_04,落成,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[越明年七月, 越明年七月]","[越明年七月, 越明年七月]",None,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_4,橋落成,0.707856,KR4d0466-WYG-f011-0010_4,橋落成,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('越明年七月', '越明年七月')","('越明年七月', '越明年七月')","((month,7),(month,7))"
11,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[甲午, 甲午]","[甲午, 甲午]",None,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_1,橋燬,0.155878,KR4d0466-WYG-f011-0010_1,橋燬,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('至元丙子', '至元丙子')","('至元丙子', '至元丙子')",NaN
12,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[至元丙子, 至元丙子]","[至元丙子, 至元丙子]",None,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,INSCR-KR4d0466-WYG-f011-0010.json,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,0.020504,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('一九二一年', '一九二一年')","('一九二一年', '一九二一年')",NaN
13,INSCR-KR4d0466-WYG-f011-0010_03,始事,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[癸已十一月, 癸已十一月]","[癸已十一月, 癸已十一月]",None,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_3,橋始事,0.686363,KR4d0466-WYG-f011-0010_3,橋始事,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('癸已十一月', '癸已十一月')","('癸已十一月', '癸已十一月')","((month,11),(month,11))"
14,INSCR-KR4d0466-WYG-f011-0010_04,落成,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[越明年七月, 越明年七月]","[越明年七月, 越明年七月]",None,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_4,橋落成,0.707856,KR4d0466-WYG-f011-0010_4,橋落成,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('越明年七月', '越明年七月')","('越明年七月', '越明年七月')","((month,7),(month,7))"
15,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[甲午, 甲午]","[甲午, 甲午]",None,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_1,橋燬,0.155878,KR4d0466-WYG-f011-0010_1,橋燬,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('至元丙子', '至元丙子')","('至元丙子', '至元丙子')",NaN
16,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[至元丙子, 至元丙子]","[至元丙子, 至元丙子]",None,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,INSCR-KR4d0466-WYG-f011-0010.json,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,0.020504,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('一九二一年', '一九二一年')","('一九二一年', '一九二一年')",NaN
17,INSCR-KR4d0466-WYG-f011-0010_03,始事,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[癸已十一月, 癸已十一月]","[癸已十一月, 癸已十一月]",None,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_3,橋始事,0.686363,KR4d0466-WYG-f011-0010_3,橋始事,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('癸已十一月', '癸已十一月')","('癸已十一月', '癸已十一月')","((month,11),(month,11))"
18,INSCR-KR4d0466-WYG-f011-0010_04,落成,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[越明年七月, 越明年七月]","[越明年七月, 越明年七月]",None,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_4,橋落成,0.707856,KR4d0466-WYG-f011-0010_4,橋落成,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('越明年七月', '越明年七月')","('越明年七月', '越明年七月')","((month,7),(month,7))"
19,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[甲午, 甲午]","[甲午, 甲午]",None,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_1,橋燬,0.155878,KR4d0466-WYG-f011-0010_1,橋燬,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('至元丙子', '至元丙子')","('至元丙子', '至元丙子')",NaN
20,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[至元丙子, 至元丙子]","[至元丙子, 至元丙子]",None,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,INSCR-KR4d0466-WYG-f011-0010.json,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,0.020504,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('一九二一年', '一九二一年')","('一九二一年', '一九二一年')",NaN
21,INSCR-KR4d0466-WYG-f011-0010_03,始事,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[癸已十一月, 癸已十一月]","[癸已十一月, 癸已十一月]",None,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_3,橋始事,0.686363,KR4d0466-WYG-f011-0010_3,橋始事,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('癸已十一月', '癸已十一月')","('癸已十一月', '癸已十一月')","((month,11),(month,11))"
22,INSCR-KR4d0466-WYG-f011-0010_04,落成,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[越明年七月, 越明年七月]","[越明年七月, 越明年七月]",None,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_4,橋落成,0.707856,KR4d0466-WYG-f011-0010_4,橋落成,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('越明年七月', '越明年七月')","('越明年七月', '越明年七月')","((month,7),(month,7))"
23,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[甲午, 甲午]","[甲午, 甲午]",None,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_1,橋燬,0.155878,KR4d0466-WYG-f011-0010_1,橋燬,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('至元丙子', '至元丙子')","('至元丙子', '至元丙子')",NaN
24,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[至元丙子, 至元丙子]","[至元丙子, 至元丙子]",None,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,INSCR-KR4d0466-WYG-f011-0010.json,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,0.020504,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('一九二一年', '一九二一年')","('一九二一年', '一九二一年')",NaN
25,INSCR-KR4d0466-WYG-f011-0010_03,始事,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[癸已十一月, 癸已十一月]","[癸已十一月, 癸已十一月]",None,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_3,橋始事,0.686363,KR4d0466-WYG-f011-0010_3,橋始事,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('癸已十一月', '癸已十一月')","('癸已十一月', '癸已十一月')","((month,11),(month,11))"
26,INSCR-KR4d0466-WYG-f011-0010_04,落成,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[越明年七月, 越明年七月]","[越明年七月, 越明年七月]",None,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_4,橋落成,0.707856,KR4d0466-WYG-f011-0010_4,橋落成,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('越明年七月', '越明年七月')","('越明年七月', '越明年七月')","((month,7),(month,7))"
27,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[甲午, 甲午]","[甲午, 甲午]",None,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_1,橋燬,0.155878,KR4d0466-WYG-f011-0010_1,橋燬,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('至元丙子', '至元丙子')","('至元丙子', '至元丙子')",NaN
28,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[至元丙子, 至元丙子]","[至元丙子, 至元丙子]",None,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,INSCR-KR4d0466-WYG-f011-0010.json,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,0.020504,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('一九二一年', '一九二一年')","('一九二一年', '一九二一年')",NaN
29,INSCR-KR4d0466-WYG-f011-0010_03,始事,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[癸已十一月, 癸已十一月]","[癸已十一月, 癸已十一月]",None,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_3,橋始事,0.686363,KR4d0466-WYG-f011-0010_3,橋始事,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('癸已十一月', '癸已十一月')","('癸已十一月', '癸已十一月')","((month,11),(month,11))"
30,INSCR-KR4d0466-WYG-f011-0010_04,落成,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[越明年七月, 越明年七月]","[越明年七月, 越明年七月]",None,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_4,橋落成,0.707856,KR4d0466-WYG-f011-0010_4,橋落成,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('越明年七月', '越明年七月')","('越明年七月', '越明年七月')","((month,7),(month,7))"
31,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[甲午, 甲午]","[甲午, 甲午]",None,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_1,橋燬,0.155878,KR4d0466-WYG-f011-0010_1,橋燬,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('至元丙子', '至元丙子')","('至元丙子', '至元丙子')",NaN
32,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[至元丙子, 至元丙子]","[至元丙子, 至元丙子]",None,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,INSCR-KR4d0466-WYG-f011-0010.json,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,0.020504,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('一九二一年', '一九二一年')","('一九二一年', '一九二一年')",NaN
33,INSCR-KR4d0466-WYG-f011-0010_03,始事,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[癸已十一月, 癸已十一月]","[癸已十一月, 癸已十一月]",None,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_3,橋始事,0.686363,KR4d0466-WYG-f011-0010_3,橋始事,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('癸已十一月', '癸已十一月')","('癸已十一月', '癸已十一月')","((month,11),(month,11))"
34,INSCR-KR4d0466-WYG-f011-0010_04,落成,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[越明年七月, 越明年七月]","[越明年七月, 越明年七月]",None,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_4,橋落成,0.707856,KR4d0466-WYG-f011-0010_4,橋落成,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('越明年七月', '越明年七月')","('越明年七月', '越明年七月')","((month,7),(month,7))"
35,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[甲午, 甲午]","[甲午, 甲午]",None,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_1,橋燬,0.155878,KR4d0466-WYG-f011-0010_1,橋燬,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('至元丙子', '至元丙子')","('至元丙子', '至元丙子')",NaN
36,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[至元丙子, 至元丙子]","[至元丙子, 至元丙子]",None,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,INSCR-KR4d0466-WYG-f011-0010.json,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,0.020504,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('一九二一年', '一九二一年')","('一九二一年', '一九二一年')",NaN
37,INSCR-KR4d0466-WYG-f011-0010_03,始事,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[癸已十一月, 癸已十一月]","[癸已十一月, 癸已十一月]",None,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_3,橋始事,0.686363,KR4d0466-WYG-f011-0010_3,橋始事,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('癸已十一月', '癸已十一月')","('癸已十一月', '癸已十一月')","((month,11),(month,11))"
38,INSCR-KR4d0466-WYG-f011-0010_04,落成,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[越明年七月, 越明年七月]","[越明年七月, 越明年七月]",None,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_4,橋落成,0.707856,KR4d0466-WYG-f011-0010_4,橋落成,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('越明年七月', '越明年七月')","('越明年七月', '越明年七月')","((month,7),(month,7))"
39,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[甲午, 甲午]","[甲午, 甲午]",None,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_1,橋燬,0.155878,KR4d0466-WYG-f011-0010_1,橋燬,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('至元丙子', '至元丙子')","('至元丙子', '至元丙子')",NaN
40,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[至元丙子, 至元丙子]","[至元丙子, 至元丙子]",None,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,INSCR-KR4d0466-WYG-f011-0010.json,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,0.020504,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('一九二一年', '一九二一年')","('一九二一年', '一九二一年')",NaN
41,INSCR-KR4d0466-WYG-f011-0010_03,始事,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[癸已十一月, 癸已十一月]","[癸已十一月, 癸已十一月]",None,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_3,橋始事,0.686363,KR4d0466-WYG-f011-0010_3,橋始事,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('癸已十一月', '癸已十一月')","('癸已十一月', '癸已十一月')","((month,11),(month,11))"
42,INSCR-KR4d0466-WYG-f011-0010_04,落成,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[越明年七月, 越明年七月]","[越明年七月, 越明年七月]",None,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_4,橋落成,0.707856,KR4d0466-WYG-f011-0010_4,橋落成,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('越明年七月', '越明年七月')","('越明年七月', '越明年七月')","((month,7),(month,7))"
43,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[甲午, 甲午]","[甲午, 甲午]",None,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_1,橋燬,0.155878,KR4d0466-WYG-f011-0010_1,橋燬,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('至元丙子', '至元丙子')","('至元丙子', '至元丙子')",NaN
44,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[至元丙子, 至元丙子]","[至元丙子, 至元丙子]",None,INSCR-KR4d0466-WYG-f011-0010_01,燬焉／中厄於數,INSCR-KR4d0466-WYG-f011-0010.json,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,0.020504,SPSP192708311019_4,黃倩鴻赴美留學卒業於新英倫音樂專科學院,"[{'filename': 'SPSP192708311019.txt', 'time_re...","('一九二一年', '一九二一年')","('一九二一年', '一九二一年')",NaN
45,INSCR-KR4d0466-WYG-f011-0010_03,始事,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[癸已十一月, 癸已十一月]","[癸已十一月, 癸已十一月]",None,INSCR-KR4d0466-WYG-f011-0010_03,始事,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_3,橋始事,0.686363,KR4d0466-WYG-f011-0010_3,橋始事,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('癸已十一月', '癸已十一月')","('癸已十一月', '癸已十一月')","((month,11),(month,11))"
46,INSCR-KR4d0466-WYG-f011-0010_04,落成,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[越明年七月, 越明年七月]","[越明年七月, 越明年七月]",None,INSCR-KR4d0466-WYG-f011-0010_04,落成,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_4,橋落成,0.707856,KR4d0466-WYG-f011-0010_4,橋落成,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('越明年七月', '越明年七月')","('越明年七月', '越明年七月')","((month,7),(month,7))"
47,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,"[{'filename': 'INSCR-KR4d0466-WYG-f011-0010', ...","[甲午, 甲午]","[甲午, 甲午]",None,INSCR-KR4d0466-WYG-f011-0010_05,橋始復,INSCR-KR4d0466-WYG-f011-0010.json,KR4d0466-WYG-f011-0010_1,橋燬,0.155878,KR4d0466-WYG-f011-0010_1,橋燬,"[{'filename': 'KR4d0466-WYG-f011-0010.txt', 't...","('至元丙子', '至元丙子')","('至元丙子', '至元丙子')",NaN

In [195]:
result.head()
len(result)

48

In [196]:
# Flag match status
result["match_status"] = "matched"
result.loc[result["event_id_schema"].isna(), "match_status"] = "source_only"
result.loc[result["event_id_source"].isna(), "match_status"] = "schema_only"

result["match_status"].value_counts()

match_status
matched    48
Name: count, dtype: int64